### ISSUE TITLE
CSD windows

### ISSUE THREAD

**Issue by developer91234** [matinlotfali/KDE-Rounded-Corners#102]
Would be nice to be able to apply rounding to windows that provide their own decorations without having to write kwin+breeze rules for each one.

**Comment by matinlotfali** [comment]
Can you give me an example so I could start working on it?
I am planning to add inclusion and exception lists it would be a great help to have an example.

**Comment by developer91234** [comment]
You could launch VSCode with the custom titlebar. 

Open Settings (File -> Preferences -> Settings, then search for  `window.titleBarStyle` and change to `custom` if it's set to native)

For some reason, Chromium with gets rounded (sometimes) but that's probably cause I have this gtk3-classic patch installed which I can't remove at the moment to test. So you could also try it with Chromium and uncheck `Use system title bar and borders` by right-clicking an empty space in the tab bar, which would give you the CSD chromium window.

**Comment by matinlotfali** [comment]
@developer91234  Can you check #103 and see if it serves what you need?
You can put the windows without decoration, e.g. vscode, inside the inclusion list so it would get rounded corners.

Note that if the window doesn't have a shadow, I also can't draw a shadow for it (yet).

**Comment by RomanKode** [comment]
touching back on this topic, will the "inclusion & exclusion" allow applications like steam to have rounded corners too?

**Comment by RomanKode** [comment]
@matinlotfali I just tested your new branch "add-inclusion-exclusion", it's working correctly except it does not see flatpak applications that have CSD, I can also see why you chose to exclude CSD windows.

**Comment by matinlotfali** [comment]
Can you name some flatpak applications that have CSD? I tried it on Code-OSS flatpak and it worked fine.

**Comment by RomanKode** [comment]
GtkStressTesting is a CSD app based on GTK3 and Easy Effects is a CSD app based on GTK4

**Comment by matinlotfali** [comment]
Both of these apps have rounded corners for me. Are they not on your system?
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/7337168/7fa506c0-9e5c-411b-8e75-e6e707853b76)

**Comment by RomanKode** [comment]
It's weird, I'm on Garuda Linux, Using Plasma Wayland and for some reason CSD/Gnome apps are not seen by your plugin on my system, don't know why this is happening.
![Screenshot_20230807_020012](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/70252656/19648186-c13f-40e8-8637-68c9e4acff71)
![Screenshot_20230807_020239](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/70252656/59cf64c8-eb41-4764-85b7-7216f730fd27)
![Screenshot_20230807_020315](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/70252656/8bd1359b-b606-4c92-94b2-c10bbcd2f9e6)

**Comment by matinlotfali** [comment]
Okay I confirm that on Wayland, the GtkStressTesting and EasyEffects didn't have the rounded corner effect. I lookup the window list and I noticed a python3.10 item that I added into the inclusion list, it enabled the effect on GtkStressTesting app. But not the EasyEffects.
EasyEffects still had the GTK4 rounded corners though. But not the KDE-Rounded-Corners

**Comment by matinlotfali** [comment]
Maybe you could achieve what you need by switching to X11.

**Comment by matinlotfali** [comment]
That's fantastic. Thanks for sharing the resolution.

**Comment by developer91234** [comment]
I can't test it right now but I assume it works on x11. Let me know when if you're able to apply the shadows to the CSD windows as well and I'll be sure to test it out.

**Comment by matinlotfali** [comment]
Sadly, I can't force KWin to draw shadows if even the window doesn't originally come with the shadow (without the KDE-Rounded-Corners effect).
If I draw shadows directly on the screen (not just the window), that could affect the performance and introduce a lot more bugs as it does on LightlyShaders.
