### ISSUE TITLE
Hide Rounded corners when window is tiled

### ISSUE THREAD

**Issue by Ilya-JBR** [matinlotfali/KDE-Rounded-Corners#104]
It would be nice if this effect could hide rounded corners and made them sharp when tiled, because for now it makes tiled windows ugly and unfinished.

![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/91881001/3b15704c-53a4-4c15-8992-7d809216c515)

thanks for your work!

**Comment by matinlotfali** [comment]
Please test #105

**Comment by Ilya-JBR** [comment]
Wow! really thanks for the quick response and commit!!!

There are two problems:
1. Upper Rounded Borders doesn't get hidden(upper left, upper right)
2. It also hides the outline which is not so nice

![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/91881001/7595a00b-6cfc-4a40-bda3-d71675395ac6)

anyway thanks for your amazing work

**Comment by Ilya-JBR** [comment]
And also please make this an option not a permanent thing because Kwin projects like [Polonium](https://github.com/zeroxoneafour/polonium) uses kde plasma's own tiling system to create a tiling window manager like environment.

**Comment by Ilya-JBR** [comment]
I think this can be done be better if it was more of function that runs automatically when tiling function gets called, and not checking for it whole time, It would be more responsive  (the same thing that happens when a window gets maximized). and only apply shader when window calls untile function, like a hook.

**Comment by matinlotfali** [comment]
> 1. There is something wrong with the responsiveness

I am using windowAdded, windowRemoved, finishedResize, and maximizeChanged signals to check the tiling state. So it wouldn't check for the tiling state when dragging or resizing your window. Can you confirm that the responsiveness issue is only on the tiling branch and not the master branch?

> It also hides the outline which is not so nice
> And also please make this an option not a permanent thing

I can add multiple checkboxes inside the effect configuration so anyone can enable or disable them as they like.

> I think this can be done be better if it was more of function that runs automatically when tiling function gets called

Yeah, I looked around the KWinEffect library and I couldn't find any signal function for tiling. So I had to calculate the position of all windows and their tiling state myself. But I made sure that this doesn't happen in every frame but on windowAdded, windowRemoved, finishedResize, and maximizeChanged signals

**Comment by Ilya-JBR** [comment]
> I am using windowAdded, windowRemoved, finishedResize, and maximizeChanged signals to check the tiling state. So it wouldn't check for the tiling state when dragging or resizing your window. Can you confirm that the responsiveness issue is only on the tiling branch and not the master branch?
>
yes, there is no responsiveness problem at master branch, but because windows needs be added, removed resized and etc, to corners to be hide its not as responsive, there is too much overhead.
> 
> I can add multiple checkboxes inside the effect configuration so anyone can enable or disable them as they like.
> 
splendid, One for hiding corners, and one for hiding outlines would be enough i guess.
> 
> Yeah, I looked around the KWinEffect library and I couldn't find any signal function for tiling. So I had to calculate the position of all windows and their tiling state myself. But I made sure that this doesn't happen in every frame but on windowAdded, windowRemoved, finishedResize, and maximizeChanged signals
>
Its better to look at the polonium ways of checking for tiled maybe there is a better way because polonium may not be as stable, but its responsive.

**Comment by matinlotfali** [comment]
> One for hiding corners, and one for hiding outlines would be enough i guess.

Please check my latest commit [666a53d](https://github.com/matinlotfali/KDE-Rounded-Corners/pull/105/commits/666a53d84758b10c68ba73858f6d1cdd7e4c75da) in pull request #105 
It adds two checkboxes in the settings.

Also, when both checkboxes are disabled, the tiling calculation gets disabled. Can you confirm that with the tiling calculation disabled, the responsiveness improves? If yes, I probably need to speedup my algorithm.

**Comment by Ilya-JBR** [comment]
Yeah it seems, there is a bug in one of these commits, one question are you using wayland?, cause I only tested this on wayland and it makes all windows to be completely plane black (color maybe relate to the my color scheme). You should switch to wayland if not using it because in plasma6 the default will be wayland

**Comment by matinlotfali** [comment]
I am using X11 as a daily driver and I am also testing the effect on Wayland. I did some more testing on Wayland and I had no issue with it. I also don't see a difference between responsiveness when the effect is enabled or disabled.

**Comment by matinlotfali** [comment]
May I have more people testing this to make sure it doesn't effect responsiveness?
