### ISSUE TITLE
KF5ConfigCoreConfig.cmake error

### ISSUE THREAD

**Issue by micush** [matinlotfali/KDE-Rounded-Corners#106]
Hi,

I'm trying to install on Kubuntu 22.04.3 by following the posted instructions and I'm getting the following error:

\------------------------------------------------------------------------------------------------------------------------------------------
cmake .. --install-prefix /usrCMake Error at /usr/share/cmake-3.22/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "FindKF5ConfigCore.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "KF5ConfigCore", but CMake did not find one.

  Could not find a package configuration file provided by "KF5ConfigCore"
  (requested version 5.89) with any of the following names:
\
    KF5ConfigCoreConfig.cmake
    kf5configcore-config.cmake

  Add the installation prefix of "KF5ConfigCore" to CMAKE_PREFIX_PATH or set
  "KF5ConfigCore_DIR" to a directory containing one of the above files.  If
  "KF5ConfigCore" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/KWinEffects/KWinEffectsConfig.cmake:40 (find_dependency)
  CMakeLists.txt:50 (find_package)

-- Configuring incomplete, errors occurred!
\------------------------------------------------------------------------------------------------------------------------------------------

I've tried to 'find' these files  in the filesystem but they're not there. Any insights or pointers? I have it installed successfully on another host running Kubuntu 23.04 and it works great. I'd also like to install on my Kubuntu 22.04 host as well.

Regards,

micush

**Comment by RomanKode** [comment]
Did you try installing this package? 
`libkf5configcore5`
 if there is a devel version of it install that too.

**Comment by micush** [comment]
I installed a fresh copy of Kubuntu 22.04 and followed the installation instructions with the same end result. Kubuntu 23.04 works find though.

**Comment by RomanKode** [comment]
> I installed a fresh copy of Kubuntu 22.04 and followed the installation instructions with the same end result. Kubuntu 23.04 works find though.
![Screenshot_20230817_212121](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/70252656/4063d47f-748b-433f-a378-44e984435fda)
I did not look correctly but that version is not supported as is, you need to install kubuntu-backport repos to get it working.

**Comment by RomanKode** [comment]
https://ubunlog.com/en/habilitar-los-backports-kubuntu/

**Comment by micush** [comment]
Ah yes, my bad. I didn't understand the graphic. I tried backports with the same error. No problem. If it doesn't work on 22.04 then that's the way it is. Thanks for the suggestions. Much appreciated.

**Comment by matinlotfali** [comment]
Thank you @RomanKode for responding. The effect is working on kubuntu backports enabled. Without backports, libraries are too old and a lot of work to maintain.

**Comment by micush** [comment]
Hi. I found it necessary to use backports-extra to get this working on Kubuntu 22.04, not just backports.

add-apt-repository -y ppa:kubuntu-ppa/backports-extra

**Comment by matinlotfali** [comment]
@micush May I ask you to open a pull request and update the README.md and mention this requirement?
