### ISSUE TITLE
Add instructions for NixOS

### ISSUE THREAD

**Issue by lomenzel** [matinlotfali/KDE-Rounded-Corners#107]
may be related to #87 
after the last update in nixOS the effect dissapeard from the settings menu and is not active anymore, version 0.3.0 still works but 0.4.0 is not there anymore

**Comment by matinlotfali** [comment]
Is this happening when you run a clean build?
Also, make sure you use the correct prefix: `cmake .. --install-prefix /usr`

**Comment by lomenzel** [comment]
i cant build it myself, nixos does it. on a clean install it works, after the update i had to install the older nixpackage
nix-env -iA nixos.kde-rounded-corners
and than the current one
nix-env -iA nixpkgs-unstable.kde-rounded-corners
after deleting the package
nix-env -e kde-rounded-corners
and include it again in the configuration.nix
now it works again. iguess with these steps i somehow forced a reinstall. i really dont know what is happening. cant reproduce it anymore

**Comment by matinlotfali** [comment]
So I suggest renaming the issue to add instructions for NixOS and ask for more help from the community.
