### ISSUE TITLE
Second outline?

### ISSUE THREAD

**Issue by Akselmo** [matinlotfali/KDE-Rounded-Corners#109]
Hi, this effect is pretty cool and I like using it.

However, I would like to have two outlines: 
1. The inner one is the current one
2. Outer 1px width outline that is just plain black

This screenshot is from Aurorae theme I made from Arc Dark Aurorae, but basically this is the effect I am after

![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/13801236/49e450b6-ffb1-4642-b41a-fd18f94ed93a)

I actually wouldn't mind implementing this! However, I have no idea where to even begin. I don't really understand where the outline is drawn in the shader code, and I don't have much experience on shaders in the first place.

So if anyone could point me in right direction, I could implement it and make a setting for it, then contribute upstream, if this is a feature you're interested in having :) Even if not, I wouldn't mind making the effect for myself.

Thanks!

**Comment by matinlotfali** [comment]
I like this very much!
You are absolutely right that the code is documented very poorly. So before we begin on this, as I already mentioned in another pull request #101, I should add documentation on the current implementation and enable others to contribute more effectively.

**Comment by Akselmo** [comment]
Sounds good to me, I have time to work on this whenever.

**Comment by matinlotfali** [comment]
@Akselmo I added a lot of comments for you in #121

**Comment by Akselmo** [comment]
Thanks, will give it a looksie!

**Comment by SATYADAHAL** [comment]
@Akselmo  any progress on second outline?

**Comment by Akselmo** [comment]
Sorry ive been so busy i forgot. I could try this on weekend possibly but cant promise anything. If someone else wants to make this, go right ahead :)

**Comment by matinlotfali** [comment]
Let's test #230

**Comment by SATYADAHAL** [comment]
Works like a charm @matinlotfali 
Thanks for maintaining this project.
KDE rounded corner must be there by default in desktop effects.
