### ISSUE TITLE
There is a "border" below the window and the window border is still shown in the title bar even though it is disabled.

### ISSUE THREAD

**Issue by eexsty** [matinlotfali/KDE-Rounded-Corners#11]
![image](https://user-images.githubusercontent.com/45243386/140652509-3cb2bbd1-4b09-461c-b84e-83ff4ecf3280.png)

**Comment by matinlotfali** [comment]
Is it also happening with breeze window border style? What distribution are you using?

**Comment by matinlotfali** [comment]
@eexsty Any news on this? Is this issue resolved?
