### ISSUE TITLE
apply effect based to other  window attributes, especially window type

### ISSUE THREAD

**Issue by developer91234** [matinlotfali/KDE-Rounded-Corners#110]
The effect produces unwanted sideeffects for menus and other non-standard windows. It would be beneficial to have the ability to fine tune the effect so that inclusions and exclusion only applies to windows of a certain type, as you can do with kwin rules. For example I'd like to be able to exclude menus of a certain app but not the main window.

**Comment by matinlotfali** [comment]
@developer91234 
Can you name a specific app so I can focus on and read debug logs?

**Comment by developer91234** [comment]
TradingView's one example, but it's kind of a big package. When you open the triple dot menu, you get an artifact.

I don't really care about particular apps though, I just think that in general it's a good idea to be able to apply the effect based on window type and not just class.

![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/43324854/baac8a60-4439-4bed-8637-b4c81ac58cb9)

**Comment by matinlotfali** [comment]
I am only drawing the effect if the window already reports that it has a decoration. I am also under the assumption that a menu will never have a decoration. That is why I would like to check debug logs on TradingView and see the contents of variables.

**Comment by phsoucy** [comment]
Hi,

I have the same issue in the menus of Dolphin.

**Comment by phsoucy** [comment]
Fixed it by deleting Dolphin from Included Windows!

![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/55606724/7a5e9336-a9de-4d09-a89b-ca347d261a21)

**Comment by matinlotfali** [comment]
@developer91234 @phsoucy  pull request #118 fixes the issue
