### ISSUE TITLE
KF5WindowSystem doesn't accept newer versions

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [matinlotfali/KDE-Rounded-Corners#112]
```
-- Found KF5WindowSystem: /usr/lib64/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.109.0") 
CMake Error at /usr/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find KF5 (missing: GlobalAccel) (found suitable version
  "5.109.0", minimum required is "5.78")
Call Stack (most recent call first):
  /usr/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:93 (find_package_handle_standard_args)
  CMakeLists.txt:40 (find_package)
```
Either it's an issue with the CMakeList not really noticing 5.109.0 is a newer version compared to 5.78, or… it's confused with the additional `.0` at the end.
Been trying to compile it on Solus.

**Comment by matinlotfali** [comment]
Looks like an issue with the ECM or cmake package that is maintained by Solus.
One possible solution is to change the CMakeList.txt file and replace line 5 with:

    set(KF5_MIN_VERSION "5.109.0")

**Comment by PoorPocketsMcNewHold** [comment]
I did quickly closed this issue, as it instead, was an issue with the `Missing GlobalAccel` part of the depedencies
I did thought of modifying CMakeList but so far, installing the missed dependency did the trick.
_(Sadly, I've experimented to much with installing so many ones that i couldn't determine which one it was, nor a definitive list of dependencies needed for Solus as a Pull-request, without pulling plenty of actually unneeded ones)._
