### ISSUE TITLE
Active Shadow -> Use Decoration Color -> Highlight should automatically change with the system

### ISSUE THREAD

**Issue by micush** [matinlotfali/KDE-Rounded-Corners#113]
The System Settings -> Appearance -> Colors -> Use accent color: From current wallpaper is pretty handy. It makes theming based on wallpaper quite nice.

Requesting that ShapeCorners -> Properties -> Active Shadow -> Use Decoration Color: Highlight change dynamically just like the system accent color.

Or maybe even a "Use system colors" checkbox for all options that dynamically changes when the system accent colors change would be helpful. I shouldn't need to log out and then back in to get the shadows and outlines to change when all the system colors do it automatically.

**Comment by RomanKode** [comment]
This should be done to both outline and shadows, I do not know if Kwin has some sort of API that can send a "signal" to a kwin script/effect that tell it that the colorscheme has been changed. if there is then that would save a lot of overhead on the effect not having to constantly watch for a colorscheme update.

**Comment by matinlotfali** [comment]
@micush @RomanKode The pull request #119 fixes the issue.

**Comment by RomanKode** [comment]
> @micush @RomanKode The pull request #119 fixes the issue.

Can you explain how does it work because I change the accent color on settings and the outline color does not update untill I disable effect then enable it.

**Comment by matinlotfali** [comment]
> I change the accent color on settings and the outline color does not update untill I disable effect then enable it

Make sure you pull the latest commit and clean build the effect.
