### ISSUE TITLE
Any way to whitelist all programs? (Apply rounded corners to all applications)

### ISSUE THREAD

**Issue by probablynotyasho** [matinlotfali/KDE-Rounded-Corners#114]
Hello

So I've been using it for a while and it works well but it's a bit of an annoyance when you install a new program and you have to manually go to the settings and include it in the ShapeCorners effect. Is there a way to apply this effect to every single window? 

![Screenshot](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/90166733/2fccec49-fff3-4fbe-b793-aa6dadc80ff8)

Thank you for maintaining this btw

**Comment by matinlotfali** [comment]
Yes, I have been thinking about this feature as well. I can add a checkbox to include all.

**Comment by NotYasho** [comment]
good idea

**Comment by matinlotfali** [comment]
@NotYasho according to the code below: https://github.com/matinlotfali/KDE-Rounded-Corners/blob/e78416625f05596d4ee6eee6292ed76f774d65cf/src/ShapeCornersEffect.cpp#L178
I am applying the effect to any window that has native decorations. This should naturally include some of the windows in your inclusion list such as konsole, dolphin, filelight.

So I am wondering, is it another effect that is changing the hasDecoration() return value to false?

**Comment by SATYADAHAL** [comment]
Whitelisting is a good idea. I want rounded corners for Picture-In-Picture mode in Firefox. I temporarily tweaked window rules, adding a title bar to it. It breaks the original idea a bit, but it's better than sharp corners. Some apps would look nicer without a title bar and with rounded corners. Hoping for those changes soon!
![Screenshot_20231215_152955](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/51309409/193ceb8a-ea88-4879-9dfd-9796f661d98c)

**Comment by hrqmonteiro** [comment]
> Whitelisting is a good idea. I want rounded corners for Picture-In-Picture mode in Firefox. I temporarily tweaked window rules, adding a title bar to it. It breaks the original idea a bit, but it's better than sharp corners. Some apps would look nicer without a title bar and with rounded corners. Hoping for those changes soon! ![Screenshot_20231215_152955](https://private-user-images.githubusercontent.com/51309409/290786626-193ceb8a-ea88-4879-9dfd-9796f661d98c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMTU5MzIsIm5iZiI6MTcwNTAxNTYzMiwicGF0aCI6Ii81MTMwOTQwOS8yOTA3ODY2MjYtMTkzY2ViOGEtZWE4OC00ODc5LTlkZmQtOTc5NmY2NjFkOThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDIzMjcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMDFjNDc3NmUyYzFlODBlNjZmYmQxZGY5YjIzMGJiNjliYjRkNDVjNTg5NzA3ZjI1NmRlNjgwOGExODQ1MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QNh4pzd-hNAFEDZy12cC0CRi9fcVspDw_jEHkDZs018)

Hi, which theme is this? Please? (KDE and GTK, everything)

**Comment by SATYADAHAL** [comment]
> Hi, which theme is this? Please? (KDE and GTK, everything)

My KDE is messed up with a lot of themes and tweaks around. 
Global theme: WhiteSur-dark
ApplicationStyle: kvantum-dark
GTK theme: WhiteSur-Dark
Window Decoration: Sweet-Dark-Transparent
Kvantum Theme: WhiteSurDark
Wallpaper: https://4kwallpapers.com/images/wallpapers/macos-sonoma-6016x6016-11578.jpg

**Comment by matinlotfali** [comment]
@SATYADAHAL @probablynotyasho Can you test the pull request?
