### ISSUE TITLE
Keep round corners when entering the "all windows" screen

### ISSUE THREAD

**Issue by arnxxau** [matinlotfali/KDE-Rounded-Corners#116]
As you can see, the effect goes off when entering the overview screen. It would be more cohesive if the effect remained on all screens

Normal view
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/59172081/bfc892a8-1d9c-44cc-a345-7ce7311f612a)

Overview window
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/59172081/0cc5e353-23bd-4023-ae71-1c43b81bd47b)

**Comment by RomanKode** [comment]
From my understanding it cannot be done without coding the overview effect to include the capabilities to round the corners of all windows displayed, basically there is no "sharing" or exporting desktop effect functionality between other desktop effect for such a feature to be implemented I believe a new API would need to be written in kwin that would allow the export of features from other effects.

It would be cool if kwin were to add such feature that would allow devs to write effect libraries that could in turn be used by other effects.

**Comment by matinlotfali** [comment]
I agree with @RomanKode. 
I don't believe the overview effect can use other Kwin effects.
