### ISSUE TITLE
Rounded corners at fullscreen windows

### ISSUE THREAD

**Issue by karolproksa** [matinlotfali/KDE-Rounded-Corners#12]
As mentioned in the title. When for example playing fullscreen videos we can see the rounded corners.

**Comment by matinlotfali** [comment]
I need more information. What app do you use to see fullscreen videos? A screenshot would also be nice.

**Comment by lk-vila** [comment]
It happens to me also. I'll use vlc as an example, this is a screenshot that i just took:
![Screenshot_20211121_140500](https://user-images.githubusercontent.com/53627437/142771920-28bdf3a3-b470-4f67-a817-55a3113db8c4.png)

**Comment by matinlotfali** [comment]
Is the issue a duplicate of issue #3 ?

**Comment by MyFilippo94** [comment]
Can confirm, happened with Mozilla Firefox and MPV Player too.
This is Firefox, on Youtube
![image](https://user-images.githubusercontent.com/33789014/147283945-2bf1e995-17a8-46aa-93cc-0f2208f7c60c.png)
