### ISSUE TITLE
Error while compiling from source for ubuntu

### ISSUE THREAD

**Issue by PMohanJ** [matinlotfali/KDE-Rounded-Corners#124]
After installing the dependencies listed in the Readme file (Ubuntu section), then the following error raises while compiling . 
<img width="813" alt="Screenshot 2023-12-21 at 12 37 34 PM" src="https://github.com/matinlotfali/KDE-Rounded-Corners/assets/57227290/51d9c9e3-6cdf-4595-9902-1e6f352b4cd8">

I've checked if kf5configcore package/library has installed or not:
<img width="1188" alt="Screenshot 2023-12-21 at 12 42 19 PM" src="https://github.com/matinlotfali/KDE-Rounded-Corners/assets/57227290/a43bda62-a025-424d-b99d-f9f1facdcf56">

It seems like the file under /usr/lib/x86_64-linux-gnu/cmake/KwinEffects/KWinEffectsConfig has some following dependencies
<img width="330" alt="Screenshot 2023-12-21 at 12 37 20 PM" src="https://github.com/matinlotfali/KDE-Rounded-Corners/assets/57227290/d0e51be0-3393-4216-822f-d58b41de4411">

Any idea why it's causing this error?

System details:
- KDE Plasma version: 5.24.7
- KDE Frameworks version: 5.98.0
- KDE Qt version: 5.15.3
- KWin version: 5.24.7
- OS (Jammy/22.04)

**Comment by matinlotfali** [comment]
It looks like you haven't installed the backports PPA on your distro:

    sudo add-apt-repository ppa:kubuntu-ppa/backports-extra
    sudo apt update
    sudo apt full-upgrade
