### ISSUE TITLE
Effects disappear when switching light/dark from System Settings "Home"/"Quick Settings" panel

### ISSUE THREAD

**Issue by RedBearAK** [matinlotfali/KDE-Rounded-Corners#126]
@matinlotfali 

So this is what I was talking about on Reddit: 

QEMU/KVM virtual machine with Fedora 39 KDE Spin installed as guest OS. 

When switching the theme from Breeze Dark to Breeze Light or vice versa, from the System Settings default "Home" panel (titled "Quick Settings" at the top), the rounded corners and custom drop shadow effects go away on all existing windows, and will only appear on new windows. 

Disabling the ShapeCorners effect and clicking Apply, and then re-enabling and clicking Apply, does not restore the effect on any existing windows. The affect still ends up only being applied to newly created windows. 

Seems like some kind of Plasma or KWin bug to me. Surely the effect should have been re-applied to all existing windows after the theme/mode is changed. But it seems like the effect just can't re-apply itself onto existing windows. 

I don't usually change the dark/light mode much, but some users like to have it change automatically, using the dark mode as a "night mode" after sunset. Unless there is another way to change light vs dark that isn't affected by this glitch, all app windows would have to be closed to get the effect to start working again, every time the switch happens.

**Comment by RedBearAK** [comment]
@matinlotfali 

I'm not seeing any difference after doing a clean re-clone, build, install, on Fedora 39 KDE spin. The rounded corners and custom shadow still disappears on all existing windows after changing the theme between light and dark. Only comes back on new windows.

**Comment by matinlotfali** [comment]
It is surprising because I am sure I fixed the issue on my end as I saw it on Wayland.

I will install Fedora and I will check again.

**Comment by matinlotfali** [comment]
I just tested it on a fresh Fedora 39 VM and it worked as expected.

**Maybe you need to uninstall the older installation first.**

Switching to [v0.5.0](https://github.com/matinlotfali/KDE-Rounded-Corners/releases/tag/v0.5.0), build and install it, then run `sudo make uninstall`

Then after the previous version is uninstalled, switch to the latest `master` branch and install.

**Comment by RedBearAK** [comment]
OK, I went through all that and re-installed the new version, it still didn't re-apply the effect until I restarted the VM. I didn't try logging out first, just shut down and started it again. 

Now it seems to maintain the effects as I switch back and forth between light and dark themes from that Quick Settings panel. 👍🏽 

I guess the README already says something about logging out or replacing KWin (and mentions this will be the same as logging out with a Wayland session, since all the apps will crash/close until they enable session persistence/recovery in KDE Wayland apps). So I suppose you could say this is taken care of as well as you can take care of it, unless there is another way to force KWin to start using the new version without the log out step. 

I'll be eagerly looking forward to this getting support for Plasma 6, so I can try moving off GNOME after having solved a few other KDE issues that have been keeping me on GNOME for years now.

**Comment by RedBearAK** [comment]
Original issue resolved.
