### ISSUE TITLE
All effects was broken.

### ISSUE THREAD

**Issue by Nikita-Presnov** [matinlotfali/KDE-Rounded-Corners#13]
It brooked all kwin effects when applying settings.

**Comment by matinlotfali** [comment]
I need more information. What is your distribution?

**Comment by Nikita-Presnov** [comment]
I made a few settings in this effect and clicked apply, and then the window manager crashed and started without applying any effect.

I removed kwin settings and it helped.

Check if it breaks some settings. 

Distro KDE neon

Of the additional scripts, there was already a non-working parachute, force blur, and sticky window snapping, and maybe something else.

**Comment by matinlotfali** [comment]
I haven't been able to reproduce the issue.
