### ISSUE TITLE
Hiding window title bar disables effect

### ISSUE THREAD

**Issue by stankovictab** [matinlotfali/KDE-Rounded-Corners#130]
First off thanks for maintaining this project, and congrats on being included with Nobara 39! 🎉
The issue I'm experiencing is that the rounded corners effect isn't being applied to windows that have their title bar disabled through System Settings -> Window Decorations -> Breeze -> Window Specific Overrides -> Hide window title bar. 
The effect I'm looking for is to have a window with no title bar, but still having a rounded corner with shadow. 
Here's an example of my terminal with the effect applied with the title bar enabled. 
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/62820268/0034d092-7c44-4422-9d9f-d0b160d50979)
Here it is with "Hide window title bar" option enabled. 
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/62820268/2735c37d-ad06-4b2b-8f1c-5f078130a9c6)
It's using the default Breeze styling for the border, which isn't ideal. 
And also, using the "No titlebar and frame rule" completely gets rid of both the rounded corners effect and the default Breeze frame, but that doesn't matter as much I don't think. 
Any ideas on how to force it to use it, or if it's possible to implement?

**Comment by matinlotfali** [comment]
Try adding the `konsole` to the list of included windows in the effect settings.
Here is the location: [ System Settings ] --> [ Workspace Behavior ] --> [ Desktop Effects ] --> [ ShapeCorners ]

PS: It is great news to know the project is included in a distro. Is there a link? Do you know the package manager?

**Comment by stankovictab** [comment]
Ohh so that's how you do it, you need to force it to have the effect, thanks!
And yeah, [here's](https://nobaraproject.org/2023/12/26/december-26-2023/) the changelog for the release, it's under the "Additional misc changes" section. 
The distro is based on Fedora and focuses on gaming, and it's officially switched to KDE from this version onwards. 
The maintainer of the distro is GloriousEggroll, a big name in the linux gaming space. 
He mentions there the `plasma-rounded-corners` package, but I'm pretty sure it's a special package inside of the Nobara repos, I might be mistaken. 

I'll close off the issue, thanks again for the fast response! 😄
