### ISSUE TITLE
Doesn't work when building from the Git repository

### ISSUE THREAD

**Issue by yoonsangmin** [matinlotfali/KDE-Rounded-Corners#131]
@matinlotfali 
Hello, I sincerely thank all developers.

I encountered a problem when trying to use this project that I really like. The build is successful, and I can see the settings in the KWin effect configuration, but the functionality itself is not working.
It seems like this issue occurred recently. I noticed that it works fine when I build it with the 0.5.0 release or an older commit.

I am using Arch Linux and the KDE environment is updated to the latest from the Arch Extra repository.
The same issue occurs when building from AUR as it also points to the latest git repository version.
Therefore, I am currently building and using from a previous commit.

I'm sorry for raising an issue not from the release version.
Thank you for checking my issue despite my poor English proficiency. Thank you for your beautiful work.

**Comment by matinlotfali** [comment]
Hi @yoonsangmin 
Thanks for reaching out.

I need some logs to help you with this.
Can you send me the output of each of these build commands:

    cmake .. --install-prefix /usr

and

    make

and

    sudo make install

**Comment by matinlotfali** [comment]
Hi @yoonsangmin 
Thanks for reaching out.

You are absolutely correct. 
I fixed the issue in the latest commit.
