### ISSUE TITLE
Effect not working on included windows on X11

### ISSUE THREAD

**Issue by SATYADAHAL** [matinlotfali/KDE-Rounded-Corners#134]
I have whitelisted firefox. When i remove the window decorations of firefox while on X11,the effect is gone.
Shouldn't whiltelisted window have effect even when there's no window decoration??

## My settings
![Screenshot_20240112_111748](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/51309409/d6748fee-81eb-4dd6-a1d1-737c2a0e0ab8)

## Wayland Session without window decoration.
![Screenshot_20240112_104802](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/51309409/f444ddca-203b-4ff9-935f-0440d14719af)

## X11 Session without window decoration.
![Screenshot_20240112_105256](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/51309409/05350467-1e07-4131-9d19-4deca8d36d81)

**Comment by matinlotfali** [comment]
@SATYADAHAL Can you test the pull request?

**Comment by SATYADAHAL** [comment]
@matinlotfali included windows without decorations are working as expected.
But there is an exception with firefox. When on X11 and I try to see list of opened windows firefox is missing.
In the screenshot below. You can the firefox is opened but Its not on the list. I refreshed it to see it again but it was not working. Otherwise for all other apps that I tried its working properly.
## X11
![Screenshot_20240114_091637](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/51309409/e34251e4-a99d-4ed3-972f-d5b2c3515b09)

**Comment by matinlotfali** [comment]
I'm glad that it is working.
Firefox uses the name `navigator`.
