### ISSUE TITLE
Fedora Rawhide: cmake issues - Could NOT find KF6ConfigWidgets and Target not yet defined Qt::CorePrivate

### ISSUE THREAD

**Issue by RedBearAK** [matinlotfali/KDE-Rounded-Corners#141]
@matinlotfali 

Tried to follow the usual instructions to install on Fedora Rawhide (currently showing Plasma 6.0 RC1) and ran into the build error in the title. 

Unfortunately I can't get copy-paste working between the guest and host in this VM, so I'll have to just add a screenshot. 

![fedora_rawhide_build_error](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/64876997/f3f7efd0-9575-4837-95ba-46ce9e521afc)

**Comment by RedBearAK** [comment]
Got past this initial build error by changing all kf5/qt5 in the package list for Fedora to kf6/qt6. Surprisingly it did not complain that any of the resulting package names were missing, but there's probably something new that needs to be added, because here is the next build error. 

![fedora_rawhide_second_build_error](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/64876997/e5995616-7a98-4b2f-8f32-02559862f576)

**Comment by matinlotfali** [comment]
Yeah, I haven't prepared the dependency list of Plasma 6 in Fedora Raw-hide. I only gathered them for Neon in `README.md`.

Everything is just too fresh. It would be much faster if every distro user would start digging for their distros and open a pull request.

**Comment by RedBearAK** [comment]
This seems to indicate there might be a bug you'll need to work around, for now, but it's hard for me to tell if this is meaningful. Another link I got to mentioned some packages like `qt6-tools-dev` but I can't find anything that seems to be equivalent on Fedora except packages that are already installed. 

https://stackoverflow.com/questions/71086422/cmake-cannot-find-packages-within-qt6-installation

**Comment by matinlotfali** [comment]
@RedBearAK 
I found the dependencies in #145. Please try them out and see if I got everything needed.

**Comment by RedBearAK** [comment]
@matinlotfali 

I still get the same build error from the second screenshot after installing the new package list. About the CMake error at Qt6CoreVersionlessTargets.cmake. Tried closing the terminal and even logging out, just in case. 

Packages like `qt6-qttools-devel` were already marked as installed, and my web searches have not turned up any obvious solution for Fedora for that particular error.

**Comment by matinlotfali** [comment]
Your second screenshot is asking for `qt6-qtbase-private-devel` if you install it the error should be gone or at least change.

**Comment by RedBearAK** [comment]
> Your second screenshot is asking for qt6-qtbase-private-devel if you install it the error should be gone or at least change.

No, that was already part of your updated package list, and it did bring in a dozen or more other packages, but now it's installed and I still get the same error. 

Did you take a look at the link I posted earlier? It seemed to be talking about a problem where CMake was unable to find the installed Qt6 due to some kind of bug with Qt_DIR. There's mention of a longer environment variable that might need to be set.

**Comment by matinlotfali** [comment]
This is very strange. I started with a fresh Fedora Rawhide and cmake was successful using the packages I mentioned in `README.md`

https://github.com/matinlotfali/KDE-Rounded-Corners/blob/a77691db302396ea17eba0ae85515c2f382fb0e6/README.md?plain=1#L59-L62

**Comment by RedBearAK** [comment]
> This is very strange. I started with a fresh Fedora Rawhide and cmake was successful using the packages I mentioned in README.md

It is certainly odd. I started my VM with the KDE spin ISO from here: 

https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Spins/x86_64/iso/

Now I reset the VM to an early snapshot that should be clean, did a 1 gig update from Plasma 6 beta 2 to RC1 again, and I don't get the build error. 

However, just like on Neon Unstable, the effect does not show up after logging out. The folder structure in /usr/lib seems different, so the fix for Neon Unstable wouldn't work. There's no `x86_64-linux-gnu` folder in /usr/lib on Fedora. 

But there's /usr/lib/qt5 of /usr/lib/qt6 with a "plugins" folder inside. 

I'm surprised you still aren't seeing the same thing with the effect not installing correctly. 

Here, this seems to work: 

```sh
sudo cp -r /usr/lib64/plugins/kwin /usr/lib64/qt6/plugins/
```

That got the effect to show up. Same kind of thing, just a different base directory. 

Seeing the same partial updating when changing the shadow color, but otherwise it seems to be working.

**Comment by matinlotfali** [comment]
> I don't get the build error

That is fantastic. I am closing the issue then.

> However, just like on Neon Unstable, the effect does not show up after logging out.

I found the fix in #146. It was a dumb mistake on my side.
