### ISSUE TITLE
Plasma 6.1 Dev - [Solved] effect installed but not loading

### ISSUE THREAD

**Issue by RedBearAK** [matinlotfali/KDE-Rounded-Corners#142]
@matinlotfali 

Got this build error when trying to install on Neon Unstable, which currently displays Plasma 6.1 Dev on the desktop. 

Like the Fedora Rawhide VM, I can't get copy-paste working, so here is a screenshot. 

![neon_unstable_build_error](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/64876997/7ac77112-7df1-4773-aee7-1f22efcbfa5e)

**Comment by RedBearAK** [comment]
Got past the error by adding `extra-cmake-modules` to the Plasma 6 package list for Debian systems. 

But after the `sudo make install` nothing seems to be showing up in Desktop Effects, even after logging out.

**Comment by RedBearAK** [comment]
The "load.sh" command from the README just prints "false" in the terminal when I run it on Neon Unstable.

**Comment by matinlotfali** [comment]
I think I know the reason `sudo make install` is not adding the effect to the Desktop Effects. This is a bug that didn't exist two days ago.

With the latest Plasma 6 update, the `kcoreaddons_add_plugin` command in [here](https://github.com/matinlotfali/KDE-Rounded-Corners/blob/79ee595e3e19665bbd756aaa0b36a89d7cc4ba74/src/CMakeLists.txt#L12C1-L12C23) started installing the effect in `/usr/lib/x86_64-linux-gnu/plugins` instead of `/usr/lib/x86_64-linux-gnu/qt6/plugins`. 

If you simply run the command below, after the installation it should be able to see it:
```bash
sudo cp -r /usr/lib/x86_64-linux-gnu/plugins/kwin /usr/lib/x86_64-linux-gnu/qt6/plugins/
```

I will report the bug in [bugs.kde.org](bugs.kde.org)

**Comment by RedBearAK** [comment]
This does seem to fix the issue on Neon Unstable: 

```sh
sudo cp -r /usr/lib/x86_64-linux-gnu/plugins/kwin /usr/lib/x86_64-linux-gnu/qt6/plugins/
```

I'm seeing some oddities here and there when changing settings. I'll open a new issue thread. They are just minor observations. It is working in general on Neon Unstable after that copy command and a reboot. 👍🏽

**Comment by matinlotfali** [comment]
FYI, I openned this bug report: https://bugs.kde.org/show_bug.cgi?id=480107

**Comment by matinlotfali** [comment]
I found the issue. The issue was from my side. I feel dumb

**Comment by Kenny-Dave** [comment]
> sudo cp -r /usr/lib/x86_64-linux-gnu/plugins/kwin /usr/lib/x86_64-linux-gnu/qt6/plugins/

I don't have either of these folders on Fedora KDE. Any guidance? I do have

`/usr/lib/qt6/plugins/` : empty bar a folder 'kf6' which is also empty.

More promisingly I do have: '/usr/local/lib64/plugins/kwin/effects/plugins/kwin4_effect_shapecorners.so'

And folder `/usr/lib64/qt6/plugins/kwin/plugins/` which contains other .so files. But copying the above file to here does not fix the problem.

I had the error in the opening post, installed `extra-cmake-modules` which made it go away. I still get `false` returned from `sh ../tools/load.sh`, and logging out and back in causes a fail. 

Any guidance is appreciated; I imagine it's clear from what I've posted, but I'm very green to this.

**Comment by matinlotfali** [comment]
I guess before building, you need to run `cmake .. --install-prefix /usr` so it would install it in `/usr` and not `/usr/local`.

You can alternatively install the `rpm` package for your fedora mentioned in `README.md`

**Comment by Kenny-Dave** [comment]
> I guess before building, you need to run `cmake .. --install-prefix /usr` so it would install it in `/usr` and not `/usr/local`.
> 
> You can alternatively install the `rpm` package for your fedora mentioned in `README.md`

Thank you for the quick response. I am a wally for not seeing the rpm, that got it, much appreciated!
