### ISSUE TITLE
Fedora 39 Build installs in the wrong directory

### ISSUE THREAD

**Issue by ByteEnable** [matinlotfali/KDE-Rounded-Corners#152]
Fedora 39 builds are copying the binaries to /usr/lib64 instead of /usr/lib64/qt5/plugins/ .

Per this comment in an another issue:  https://github.com/matinlotfali/KDE-Rounded-Corners/issues/141#issuecomment-1902494513

**Comment by matinlotfali** [comment]
I need logs for this because I can't reproduce it.
Can you remove the whole `build` directory, recreate it, run the whole build and install, and copy the whole output texts in here?

**Comment by ByteEnable** [comment]
I built has root and no issues.
