### ISSUE TITLE
Even more natural shadows

### ISSUE THREAD

**Issue by developer91234** [matinlotfali/KDE-Rounded-Corners#153]
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/43324854/f729eb65-35f1-4b2a-8c64-5de3673a4e15)

Might be a good idea to shift the shadows down and increase the shadow radius by some user defined offset. This would make the shadows look more like shadows by making them stronger on the bottom and weaker around the corners.

See the menu above for an example, though its subtle.

**Comment by matinlotfali** [comment]
Let's mark this issue as closed and follow up on #191
