### ISSUE TITLE
Shadows are not appearing on almost anything

### ISSUE THREAD

**Issue by hrqmonteiro** [matinlotfali/KDE-Rounded-Corners#154]
This was working fine until idk last week.

Everything i open doesn't show the shadows, only Firefox in this example

https://github.com/matinlotfali/KDE-Rounded-Corners/assets/17055027/5671702e-be35-4481-8ea1-a3102808cae3

**Comment by matinlotfali** [comment]
I think it might be related to the window decoration you are using.
To make sure, does the issue appear on the default breeze window decoration?
