### ISSUE TITLE
[Plasma 6.0] Bug in Inclusions & Exclusions

### ISSUE THREAD

**Issue by 0xarch** [matinlotfali/KDE-Rounded-Corners#157]
Operation **adding or removing items in the included/excluded windows area** cannot be saved. Pressing the "OK" button has no effect("Apply" disabled).
The operation can be saved after changing the "Maximized Windows" option.
Plasma 6.0 RC1 , KFramework 5.248.0 , Qt 6.7.0
![图片](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/89088411/e6935d53-7c9f-45a3-b959-9ab50ce3bd3a)

**Comment by matinlotfali** [comment]
This is related to #147 with a similar fix.
