### ISSUE TITLE
some types of windows are not rounded

### ISSUE THREAD

**Issue by Blacksuan19** [matinlotfali/KDE-Rounded-Corners#159]
windows with type of dialog and kirigami based windows seem to be ignored.

examples:

Dolphin settings
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/10248473/471d20e2-c5e4-4e88-b715-064511b0a79a)

About KDE 
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/10248473/b2ccde9d-cc53-4487-8337-45bf9b4d9bfe)

Wallpaper settings 
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/10248473/48f32257-cb09-44c7-8026-516311afc147)

Discover
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/10248473/66a0f6e1-8318-4cac-bd61-01beffbf78ce)

**Comment by matinlotfali** [comment]
Does #161 resolve your issue?

**Comment by Blacksuan19** [comment]
half of it, dialog windows are now rounded, however, kirigami dialogs are still not rounded (wallpaper settings, discover) but I suspect that is a limitation of kirigami since most kwin plugins for rounded corners can't round kirigami dialogs or apps in general.

![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/10248473/05c23228-24e4-440c-bc0c-95c2b95ac12a)


![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/10248473/d1f03287-e1f3-4978-9983-2405782e4f83)

**Comment by Blacksuan19** [comment]
just noticed the effect also applies to the lockscreen now

![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/10248473/18e9f633-e9b6-437f-a028-bafec5784bf6)

**Comment by matinlotfali** [comment]
Sadly, I don't seem to be able to access Kirigami dialogs. It looks like they are drawn inside the parent window and they can not be dragged outside of the parent window.

For the lock screen, I can't reproduce it on my end. Despite that, I can exclude the `kscreenlocker_greet` and `ksmserver` from the effect.

I just pushed the latest commit in #161.

**Comment by Blacksuan19** [comment]
I can confirm the effect doesn't apply to the lockscreen anymore.
