### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by FeyrisTan** [matinlotfali/KDE-Rounded-Corners#162]
The display manager crashes a few seconds after enabling it.

Mesa 24.1.0-devel (git-5d293f01cc)

AMD Radeon RX 6800 XT

Edit: Only happens on wayland. Worked fine tho when I tried it on wayland last week.

**Comment by FeyrisTan** [comment]
Arch Linux

<details> 
  <summary> </summary>
    kwin_wayland[4080]: Module 'org.kde.kwin.decoration' does not contain a module identifier directive - it cannot be protected from external registrations.
kwin_wayland[4551]: No backend specified, automatically choosing drm
kwin_wayland[4551]: OpenGL vendor string:                   AMD
Feb 03 20:10:52 kuzu kwin_wayland[4551]: OpenGL renderer string:                 AMD Radeon RX 6800 XT (radeonsi, navi21, LLVM 16.0.6, DRM 3.57, 6.7.3-2-cachyos)
Feb 03 20:10:52 kuzu kwin_wayland[4551]: OpenGL version string:                  4.6 (Core Profile) Mesa 24.1.0-devel (git-5d293f01cc)
kwin_wayland[4551]: OpenGL shading language version string: 4.60
kwin_wayland[4551]: Driver:                                 Unknown
kwin_wayland[4551]: GPU class:                              Unknown
kwin_wayland[4551]: OpenGL version:                         4.6
kwin_wayland[4551]: GLSL version:                           4.60
kwin_wayland[4551]: Mesa version:                           24.1
kwin_wayland[4551]: Linux kernel version:                   6.7.3
kwin_wayland[4551]: Requires strict binding:                no
kwin_wayland[4551]: GLSL shaders:                           yes
kwin_wayland[4551]: Texture NPOT support:                   yes
kwin_wayland[4551]: Virtual Machine:                        no

kwin_wayland_wrapper[4614]: (WW) Option "-listen" for file descriptors is deprecated
kwin_wayland_wrapper[4614]: Please use "-listenfd" instead.
kwin_wayland_wrapper[4614]: (WW) Option "-listen" for file descriptors is deprecated
kwin_wayland_wrapper[4614]: Please use "-listenfd" instead.
kwin_wayland[4551]: ShapeCorners: shaders loaded.

kwin_wayland_wrapper[4648]: The XKEYBOARD keymap compiler (xkbcomp) reports:
kwin_wayland_wrapper[4648]: > Warning:          Could not resolve keysym XF86CameraAccessEnable
kwin_wayland_wrapper[4648]: > Warning:          Could not resolve keysym XF86CameraAccessDisable
kwin_wayland_wrapper[4648]: > Warning:          Could not resolve keysym XF86CameraAccessToggle
kwin_wayland_wrapper[4648]: > Warning:          Could not resolve keysym XF86NextElement
kwin_wayland_wrapper[4648]: > Warning:          Could not resolve keysym XF86PreviousElement
kwin_wayland_wrapper[4648]: > Warning:          Could not resolve keysym XF86AutopilotEngageToggle
kwin_wayland_wrapper[4648]: > Warning:          Could not resolve keysym XF86MarkWaypoint
kwin_wayland_wrapper[4648]: > Warning:          Could not resolve keysym XF86Sos
kwin_wayland_wrapper[4648]: > Warning:          Could not resolve keysym XF86NavChart
kwin_wayland_wrapper[4648]: > Warning:          Could not resolve keysym XF86FishingChart
kwin_wayland_wrapper[4648]: > Warning:          Could not resolve keysym XF86SingleRangeRadar
kwin_wayland_wrapper[4648]: > Warning:          Could not resolve keysym XF86DualRangeRadar
kwin_wayland_wrapper[4648]: > Warning:          Could not resolve keysym XF86RadarOverlay
kwin_wayland_wrapper[4648]: > Warning:          Could not resolve keysym XF86TraditionalSonar
kwin_wayland_wrapper[4648]: > Warning:          Could not resolve keysym XF86ClearvuSonar
kwin_wayland_wrapper[4648]: > Warning:          Could not resolve keysym XF86SidevuSonar
kwin_wayland_wrapper[4648]: > Warning:          Could not resolve keysym XF86NavInfo
kwin_wayland_wrapper[4648]: Errors from xkbcomp are not fatal to the X server

libddcutil[4572]: busno=6, All features that should not exist detected. Monitor does not indicate unsupported
</details>

**Comment by bimtenbo** [comment]
Having this same crash on Arch with my Radeon RX 7800 XT card.

**Comment by OzzyHelix** [comment]
is this related 
https://github.com/matinlotfali/KDE-Rounded-Corners/issues/165

**Comment by OzzyHelix** [comment]
this is what I get in my dmesg when my desktop crashes
```
[ 8488.006973] kwin_wayland[1190]: segfault at 0 ip 0000783aa9bf560b sp 00007fffc999b2a0 error 4 in kwin4_effect_shapecorners.so[783aa9bf4000+7000] likely on CPU 7 (core 7, socket 0)
[ 8488.006988] Code: 46 28 00 00 00 00 49 89 6e 30 49 89 6e 38 49 c7 46 40 00 00 00 00 66 0f 1f 84 00 00 00 00 00 4c 89 ee 4c 89 f7 e8 c5 ea ff ff <49> 8b 45 00 4c 89 ef ff 90 c8 00 00 00 66 0f 2f 05 78 5e 00 00 72

```

**Comment by matinlotfali** [comment]
@bimtenbo Can you try #166 to see if the crash happens?

**Comment by FeyrisTan** [comment]
Seems to work fine now have not crashed yet.

**Comment by bimtenbo** [comment]
Fixed the issue for me as well.

**Comment by FeyrisTan** [comment]
It's happening again.

**Comment by matinlotfali** [comment]
Is the error the same?
@OzzyHelix Can you share with @FeyrisTan how to get a detailed stacktrace?

**Comment by matinlotfali** [comment]
@FeyrisTan 
Please clean and build the latest `master` branch and see if it happens again.

**Comment by matinlotfali** [comment]
@FeyrisTan 
Maybe a clean building using `cmake .. --install-prefix /usr -DCMAKE_BUILD_TYPE=debug` would provide you with a more detailed segfault stack trace.

**Comment by OzzyHelix** [comment]
> Is the error the same? @OzzyHelix Can you share with @FeyrisTan how to get a detailed stacktrace?

I thought it might be but I guess not

**Comment by OzzyHelix** [comment]
it did crash once for me when I was switching inputs on my monitor but that was such a random case that I didn't feel it needed reporting because it only happened once and hasn't happened again

**Comment by OzzyHelix** [comment]
this might be a similar issue
