### ISSUE TITLE
ZorinOS: Fails installation with following error

### ISSUE THREAD

**Issue by Arridian** [matinlotfali/KDE-Rounded-Corners#164]
`$ git clone https://github.com/matinlotfali/KDE-Rounded-Corners
cd KDE-Rounded-Corners
mkdir build
cd build
cmake .. --install-prefix /usr
make
sudo make install

Cloning into 'KDE-Rounded-Corners'...
remote: Enumerating objects: 1713, done.
remote: Counting objects: 100% (266/266), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 1713 (delta 195), reused 214 (delta 173), pack-reused 1447
Receiving objects: 100% (1713/1713), 4.08 MiB | 4.60 MiB/s, done.
Resolving deltas: 100% (1107/1107), done.
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Found KF5ConfigWidgets: /usr/lib/x86_64-linux-gnu/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (found version "5.98.0") 
-- Found KF5: success (found suitable version "5.98.0", minimum required is "5.78") found components: ConfigWidgets 
CMake Error at /usr/share/cmake-3.22/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "FindKF5ConfigCore.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "KF5ConfigCore", but CMake did not find one.

  Could not find a package configuration file provided by "KF5ConfigCore"
  (requested version 5.89) with any of the following names:

    KF5ConfigCoreConfig.cmake
    kf5configcore-config.cmake

  Add the installation prefix of "KF5ConfigCore" to CMAKE_PREFIX_PATH or set
  "KF5ConfigCore_DIR" to a directory containing one of the above files.  If
  "KF5ConfigCore" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/KWinEffects/KWinEffectsConfig.cmake:40 (find_dependency)
  CMakeLists.txt:48 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/blaise/KDE-Rounded-Corners/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
`

**Comment by matinlotfali** [comment]
The error says you are missing `KF5ConfigCore`.
- Can you confirm that you have installed all dependencies for your distro?
- What is your distro?
- If you use a Debian based dirsto, can you confirm that the package `libkf5config-dev` is already installed? _This package is expected to be automatically installed by the package `libkf5configwidgets-dev `. If it is not, then we need to adjust the `README.md`_

**Comment by Arridian** [comment]
> * Can you confirm that you have installed all dependencies for your distro?
> * What is your distro?

I am running a vanilla Zorin installation with KDE.

> * If you use a Debian based distro, can you confirm that the package `libkf5config-dev` is already installed? _This package is expected to be automatically installed by the package `libkf5configwidgets-dev `. If it is not, then we need to adjust the `README.md`_

I've checked and both of these are installed, so I'm not sure what could be causing it.

**Comment by matinlotfali** [comment]
Please install the kubuntu backports PPA on any Ubuntu-based distro including ZorinOS. It is already mentioned in `README.md`.
The effect only supports the latest version of Kubuntu and not the vanilla LTS version.
