### ISSUE TITLE
The option to keep maximized windows with the effects are missing??

### ISSUE THREAD

**Issue by hrqmonteiro** [matinlotfali/KDE-Rounded-Corners#167]
Just made a fresh install of KDE and installed the effect, now the option to keep it on maximized windows is gone?

![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/17055027/7abc28d9-eff1-47b1-8a4f-7d2984dbf9b0)

**Comment by matinlotfali** [comment]
Yep it has moved to the Properties tab
