### ISSUE TITLE
Only firefox respects the unticking of Disable Outline and Borders on maximized. 

### ISSUE THREAD

**Issue by hrqmonteiro** [matinlotfali/KDE-Rounded-Corners#168]
https://github.com/matinlotfali/KDE-Rounded-Corners/assets/17055027/c4734dc4-2f70-4906-8590-1337dad48728

Only firefox respects the unticking of Disable Outline and Borders on maximized. 

All other windows will hide the outline and round borders.

**Comment by hrqmonteiro** [comment]
And it happens with default "Breeze" decoration as well


https://github.com/matinlotfali/KDE-Rounded-Corners/assets/17055027/3dd35f48-79b0-428d-b65e-930f8288b3d1

**Comment by hrqmonteiro** [comment]
This was working fine until some weeks ago. It was perfect with the windows keeping the outline and rouded when maximized, exactly what i needed. What happened?

**Comment by matinlotfali** [comment]
I can't reproduce it on the latest `master` branch. 

Please make sure you are removing the previous installation first. Use `find /usr -name "*shapecorners*.so"` to find all libraries you already have installed.
Then use `git checkout master && git pull`

**Comment by hrqmonteiro** [comment]
> I can't reproduce it on the latest `master` branch.
> 
> Please make sure you are removing the previous installation first. Use `find /usr -name "*shapecorners*.so"` to find all libraries you already have installed. Then use `git checkout master && git pull`

It was actually a fresh install of EndeavourOS, and i cloned master and installed as the readme suggested

Did that again and still the same behavior

**Comment by matinlotfali** [comment]
Okay please give me some time to install EndeavourOS on a virtual machine and try it out there.

**Comment by hrqmonteiro** [comment]
> Okay please give me some time to install EndeavourOS on a virtual machine and try it out there.

Actually happening on Manjaro as well, for reference

**Comment by hrqmonteiro** [comment]
Any news on this? The effect was looking SO GOOD when it worked a few weeks ago

**Comment by matinlotfali** [comment]
I can't reproduce this on a fresh EndavourOS virtual machine.
