### ISSUE TITLE
Build error on Tumbleweed 20240202 snapshot

### ISSUE THREAD

**Issue by RedBearAK** [matinlotfali/KDE-Rounded-Corners#169]
@matinlotfali 

I have a physical machine with Tumbleweed installed, and just did a huge system update yesterday, then installed the KDE desktop "pattern" and restarted, then attempted to build this and get the rounded corners working. 

I did pop open the OpenSUSE required packages and made sure they were installed. Then I tried the usual block of commands to git clone and build. Even after logging out and trying again, I get this build error: 

```sh
cmake .. --install-prefix /usr
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Could not set up the appstream test. appstreamcli is missing.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Found KF5ConfigWidgets: /usr/lib64/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (found version "5.114.0") 
-- Found KF5: success (found suitable version "5.114.0", minimum required is "5.78") found components: ConfigWidgets 
CMake Error at /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package):
  By not providing "FindKF5WindowSystem.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "KF5WindowSystem", but CMake did not find one.

  Could not find a package configuration file provided by "KF5WindowSystem"
  (requested version 5.102.0) with any of the following names:

    KF5WindowSystemConfig.cmake
    kf5windowsystem-config.cmake

  Add the installation prefix of "KF5WindowSystem" to CMAKE_PREFIX_PATH or
  set "KF5WindowSystem_DIR" to a directory containing one of the above files.
  If "KF5WindowSystem" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  /usr/lib64/cmake/KWinEffects/KWinEffectsConfig.cmake:42 (find_dependency)
  CMakeLists.txt:48 (find_package)


-- Configuring incomplete, errors occurred!
```

Seems pretty similar to the issue happening on Zorin in issue #164. 

Since this is not a VM, I don't have the option in this case of trying to go back to a fresh install state and re-doing the system update to get current. But the snapshot version is fully updated as of today. 

When I installed KDE I installed both the desktop pattern and the KDE applications pattern. 

In theory a new install of Tumbleweed in a VM could immediately be updated to the same snapshot state as what I have here.

**Comment by AndGuz** [comment]
You need the kwindowsystem-devel package

**Comment by RedBearAK** [comment]
@matinlotfali

> You need the kwindowsystem-devel package

Confirmed that gets through the build error (thanks @AndGuz), and the effect gets installed and works. Looks like that should be added to the requirements for OpenSUSE. 

But KWin keeps crashing after I close the effect settings and then try to go back into the effect settings a second time. Can't pinpoint anything relevant in the journal yet. I'll have to try to watch the journal in a TTY. Since it's Wayland, each crash takes down all open windows. 

Also there's no "Apply" button in the dialog at all, just "OK" and "Cancel" (and "Defaults" on the left side). Not sure how normal that is. Seems odd for a KDE dialog to not have an Apply button. 

Maybe I should open a new issue thread.

**Comment by RedBearAK** [comment]
@matinlotfali 

The crash on the second attempt to open the settings dialog is very repeatable, but the display also gets **_very_** screwed up when I switch to a TTY and then try to switch back. So it looks like it will be difficult to troubleshoot this, and it may just be a symptom of other issues with the graphics driver. 

The machine is an iMac12,2 with an AMD video card. 

```sh
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Whistler [Radeon HD 6730M/6770M/7690M XT]
01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Turks HDMI Audio [Radeon HD 6500/6600 / 6700M Series]
```

**Comment by AndGuz** [comment]
@RedBearAK Maybe it is a drivers issue, because i cannot reproduce the messed up display issue on Tumbleweed on my intel laptop :100: , im updating tumbleweed to the latest snapshot to check again

**Comment by RedBearAK** [comment]
> @RedBearAK Maybe it is a drivers issue, because i cannot reproduce the messed up display issue on Tumbleweed on my intel laptop 💯 , im updating tumbleweed to the latest snapshot to check again

I would be much more interested in whether you can reproduce the desktop crash when trying to enter the settings for the effect a second time. I'm sure the messed up screen is typical of issues that Mac graphics cards have when trying to do anything like suspend-resume. I'm less sure whether that means the second-try settings crash issue is isolated to this machine or more of a general problem.

**Comment by matinlotfali** [comment]
I just learned the crash started since this edit:

https://github.com/matinlotfali/KDE-Rounded-Corners/commit/f0c3d0cfc3a3ca134068e89331afe4cadc7ef036#diff-412bfbf67a46a62c7cbe3001b0ac9e1d0c217f6c4cdb96d74426c57c0b9a433aL59-R59

The windowClosed signal is not being called when a config dialog is closed with OK. This is strange.
I have reverted this change in the pushed commit.

**Comment by RedBearAK** [comment]
@matinlotfali 

Just confirming that after a fresh clone/build/install and log out/in, the crash when re-opening the settings is apparently gone. Tried opening the settings dialog multiple times and changing or not changing settings. 

A little detail from before was that I think the parent main system settings window would also be acting badly once the effect settings dialog was closed, and just closing that main window would  also crash the desktop. No doubt it was because the dialog was not being closed with the right signal, as you discovered. 

Seems to be good now. 👍🏽
