### ISSUE TITLE
Just want to tell that I added it to AUR, so instructions for arch just need yay -S kde-rounded-corners

### ISSUE THREAD

**Issue by Shaurya-Kalia** [matinlotfali/KDE-Rounded-Corners#17]
Here is the package https://aur.archlinux.org/packages/kde-rounded-corners . 

I can confirm it works on my arch machine with yay, and on manjaro with pamac (`pamac build kde-rounded-corners`). Maybe edit the readme file to reflect the changes.

The package directly clones from git, so shouldn't require updates unless name of github repo is changed.

Thanks.

**Comment by bscout9956** [comment]
Unsure if there are any dependencies missing but it no longer builds (to be specific it fails to link).

`[ 23%] Automatic MOC for target kwin4_shapecorners_config
AutoMoc warning
---------------
"SRC:/shapecorners.cpp"
includes the moc file "shapecorners.moc", but does not contain a Q_OBJECT, Q_GADGET, Q_NAMESPACE, Q_NAMESPACE_EXPORT, K_PLUGIN_FACTORY, K_PLUGIN_CLASS, K_PLUGIN_FACTORY_WITH_JSON or K_PLUGIN_CLASS_WITH_JSON macro.

[ 23%] Built target kwin4_shapecorners_config_autogen

AutoMoc subprocess error
------------------------
The moc process failed to compile
  "SRC:/shapecorners.cpp"
into
  "BIN:/kwin4_effect_shapecorners_autogen/include/shapecorners.moc"
included by
  "SRC:/shapecorners.cpp"
`

Earlier... Unsure if it's fine. Then:

`[ 30%] Generating ui_shapecorners_config.h
[ 38%] Generating kwineffects_interface.cpp, kwineffects_interface.h
[ 46%] Generating kwineffects_interface.moc
[ 53%] Building CXX object CMakeFiles/kwin4_shapecorners_config.dir/shapecorners_config.cpp.o
[ 61%] Building CXX object CMakeFiles/kwin4_shapecorners_config.dir/kwineffects_interface.cpp.o
[ 69%] Building CXX object CMakeFiles/kwin4_shapecorners_config.dir/kwin4_shapecorners_config_autogen/mocs_compilation.cpp.o
[ 76%] Linking CXX shared module kwin4_shapecorners_config.so
[ 76%] Built target kwin4_shapecorners_config
make: *** [Makefile:146: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: kde-rounded-corners
`

**Comment by matinlotfali** [comment]
Thank you @Shaurya-Kalia. I reflected it in README.md
@bscout9956 the issue should now be resolved in #22
