### ISSUE TITLE
Corners remain rounded when a window is maximized if it is on a monitor with a panel

### ISSUE THREAD

**Issue by winteriscariot** [matinlotfali/KDE-Rounded-Corners#171]
Noticed this on my 3 monitor setup: 

Primary monitor: 2 panels (top and bottom)
Right-hand monitor: 1 panel (top)
Left-hand monitor: no panels

When I have a window maximized on either Primary or Right-hand monitors the rounded corners don't go away (and my desktop background peaks through the corners)

If I move the same window to my Left-hand monitor (no panels) when it maximizes it properly removes the rounded corners and properly maximizes

Additionally, if I increase the width of a window in either of the monitors with panels (Primary and Right-hand) so that it touches the edges of the screen, it does not remove the rounding. It does so properly on the Left-hand monitor (no panels)

Arch Linux, latest git build (kwin-effect-rounded-corners-git 0.6.0.r24.g721b244-1) and latest Arch version of kwin (kwin 5.27.10-2)

**Comment by matinlotfali** [comment]
@winteriscariot 
I believe #172 should fix the issue. You can test the branch.
