### ISSUE TITLE
Windows darkened/subdued in HDR

### ISSUE THREAD

**Issue by kenjite1** [matinlotfali/KDE-Rounded-Corners#175]
All windows, active/inactive are subdued and darkened when HDR is enabled.

![with dedssktop effect active](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/161068748/c80ce44c-115b-464f-a280-85fee525fb30)
![with out desktop effect](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/161068748/fe67809b-3c08-441f-876f-31e50c31a533)

**Comment by murphy-freelance** [comment]
I have the exact same issue let me know if I can be of any help

**Comment by KingKrouch** [comment]
Can confirm that I have this issue as well.

**Comment by matinlotfali** [comment]
I am working on it

**Comment by Pyrathar** [comment]
Can confirm have this issue on nobara running KDE 6

**Comment by Kevadroz** [comment]
When I am moving a window the effect is still applied but the window is no longer darkened

**Comment by aaronkirschen** [comment]
To fix this, include colormanagement.glsl and use sourceEncodingToNitsInDestinationColorspace and nitsToDestinationEncoding to fix the colors in the shader code.

This is complicated by the effect supporting both Plasma 5 and 6, as I think those won’t be available in Plasma 5. 

Something like this:

```
    if (isPlasma6) {
        // Apply the HDR color management only if running in Plasma 6.
        tex = sourceEncodingToNitsInDestinationColorspace(tex);
        gl_FragColor = nitsToDestinationEncoding(tex);
    } else {
        gl_FragColor = tex;
    }
```

**Comment by GloriousEggroll** [comment]
> colormanagement.glsl

where should this be included?

**Comment by GloriousEggroll** [comment]
> It goes in the shader code; the invert effect works as an example: https://invent.kde.org/plasma/kwin/-/blob/master/src/plugins/invert/shaders/invert.frag The commit adding the change: https://invent.kde.org/plasma/kwin/-/commit/6f06bf19893bcf70b7dfa4b85c8529a2d2abdf1a

thanks, gave it a basic try without plasma5 compat but no luck:

```
From 5fe79555c4e2a7613d699fb6a50795db23c4334d Mon Sep 17 00:00:00 2001
From: GloriousEggroll <gloriouseggroll@gmail.com>
Date: Mon, 25 Mar 2024 13:01:11 -0600
Subject: [PATCH] fix
 https://github.com/matinlotfali/KDE-Rounded-Corners/issues/175

---
 src/shaders/shapecorners.frag | 10 ++++++++--
 1 file changed, 8 insertions(+), 2 deletions(-)

diff --git a/src/shaders/shapecorners.frag b/src/shaders/shapecorners.frag
index 67b7723..d1e03e8 100644
--- a/src/shaders/shapecorners.frag
+++ b/src/shaders/shapecorners.frag
@@ -1,4 +1,5 @@
 #version 110
+#include "colormanagement.glsl"
 
 uniform sampler2D front;         // The painted contents of the window.
 uniform float radius;            // The thickness of the outline in pixels specified in settings.
@@ -110,7 +111,9 @@ void main(void)
 {
     vec4 tex = texture2D(front, texcoord0);  // The RGBA of the XY pixel for the painted window
     if(tex.a == 0.0) {
-        gl_FragColor = tex;
+        // Apply the HDR color management only if running in Plasma 6.
+        tex = sourceEncodingToNitsInDestinationColorspace(tex);
+        gl_FragColor = nitsToDestinationEncoding(tex);
         return;
     }
 
@@ -163,6 +166,9 @@ void main(void)
     }
     tex *= modulation;
 
+    // Apply the HDR color management only if running in Plasma 6.
+    tex = sourceEncodingToNitsInDestinationColorspace(tex);
+
     // Send to output
-    gl_FragColor = tex;
+    gl_FragColor = nitsToDestinationEncoding(tex);
 }
-- 
2.44.0

```

**Comment by aaronkirschen** [comment]
Oh, it needs to be changed in the _core fragment as well. This worked for me:

From bfc88caa8646ce31f97f8665a0a154ef7f136a43 Mon Sep 17 00:00:00 2001
From: Aaron Kirschen <aaronkirschen@gmail.com>
Date: Mon, 25 Mar 2024 12:16:27 -0700
Subject: [PATCH] [PATCH] fix 
 https://github.com/matinlotfali/KDE-Rounded-Corners/issues/175

---
 src/shaders/shapecorners.frag      | 5 ++++-
 src/shaders/shapecorners_core.frag | 5 ++++-
 2 files changed, 8 insertions(+), 2 deletions(-)

diff --git a/src/shaders/shapecorners.frag b/src/shaders/shapecorners.frag
index 67b7723..f71def0 100644
--- a/src/shaders/shapecorners.frag
+++ b/src/shaders/shapecorners.frag
@@ -1,5 +1,7 @@
 #version 110
 
+#include "colormanagement.glsl"
+
 uniform sampler2D front;         // The painted contents of the window.
 uniform float radius;            // The thickness of the outline in pixels specified in settings.
 uniform vec2 windowSize;         // Containing `window->frameGeometry().size()`
@@ -164,5 +166,6 @@ void main(void)
     tex *= modulation;
 
     // Send to output
-    gl_FragColor = tex;
+    tex = sourceEncodingToNitsInDestinationColorspace(tex);
+    gl_FragColor = nitsToDestinationEncoding(tex);
 }
diff --git a/src/shaders/shapecorners_core.frag b/src/shaders/shapecorners_core.frag
index 6abc1af..309a064 100644
--- a/src/shaders/shapecorners_core.frag
+++ b/src/shaders/shapecorners_core.frag
@@ -1,5 +1,7 @@
 #version 140
 
+#include "colormanagement.glsl"
+
 uniform sampler2D front;         // The painted contents of the window.
 uniform float radius;            // The thickness of the outline in pixels specified in settings.
 uniform vec2 windowSize;         // Containing `window->frameGeometry().size()`
@@ -163,5 +165,6 @@ void main(void)
     tex *= modulation;
 
     // Send to output
-    fragColor = tex;
+    tex = sourceEncodingToNitsInDestinationColorspace(tex);
+    fragColor = nitsToDestinationEncoding(tex);
 }
-- 
2.44.0

**Comment by GloriousEggroll** [comment]
hurray my rounded corners are back! thanks for the quick fix!

**Comment by matinlotfali** [comment]
May I ask you all to test pull request  #193 in both plasma 5 and plasma 6?
