### ISSUE TITLE
CMake Error: The source directory "./KDE-Rounded-Corners/build/--install-prefix" does not exist.

### ISSUE THREAD

**Issue by CallumRodgers** [matinlotfali/KDE-Rounded-Corners#177]
Hi! Sorry for the probably simple question, but I'm still a newbie to Linux and installing things from source, and I ran the commands in `README.md` and it gives me this error. I successfully installed the required dependencies, and the repo was properly cloned and all, but for some reason the `cmake .. --install-prefix /usr` command gives the error in the title. What am I doing wrong?

Also I'm running ZorinOS (Ubuntu) with KDE Plasma v.5.18.8.

**Comment by matinlotfali** [comment]
Plasma 5.18 is not supported. You need the latest KDE. Please install all the KDE backports.
