### ISSUE TITLE
Jagged edges of the task switcher's rounded corners on kde6 wayland

### ISSUE THREAD

**Issue by heddxh** [matinlotfali/KDE-Rounded-Corners#178]
It is hard to capture it since calling out the task switcher need pressing ALT...

[屏幕录像_20240309_182125.webm](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/63106571/51a78095-e7cf-4426-9b0f-f5f5b8606fdc)

**Comment by matinlotfali** [comment]
What kind of task switcher is this? It seems like it is not native. Is it?

**Comment by heddxh** [comment]
It is native "big icons" task switch. And "thumbnail grid" also have this issue.
Forget to mention that is it kde6, sorry about that, I have added it on the first post.

**Comment by matinlotfali** [comment]
@heddxh 
Please check pull request #196 if it fixes the issue

**Comment by heddxh** [comment]
![图片](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/63106571/db2d5606-ec41-45f5-b8fa-ada19fff6131)
Seems like it doesn't work?

**Comment by matinlotfali** [comment]
@heddxh
Oh right, I only fixed it for X11. I have also pushed the fix for Wayland. (I think)
Can you check pull request https://github.com/matinlotfali/KDE-Rounded-Corners/pull/196 again?

**Comment by heddxh** [comment]
Fixed it! Thanks for your job!!
