### ISSUE TITLE
Maximized windows against screen edge should not be rounded

### ISSUE THREAD

**Issue by josh1244** [matinlotfali/KDE-Rounded-Corners#18]
When a window is maximized, then the corners should not be rounded and filled in to the screen but this only happens when the window is changed from normal to maximized. If a window is opened in the maximized state, then it will still be rounded. Also if a window like Yakuake is up against the edge of the screen, them those edges should not be rounded.

**Comment by matinlotfali** [comment]
I believe this issue is fixed in the linked pull request. Feel free to reopen the issue if it is not.

**Comment by matinlotfali** [comment]
I am reopening this issue. Can you send me a screenshot and tell me what distro are you using right now?

**Comment by sheeepdev** [comment]
> I am reopening this issue. Can you send me a screenshot and tell me what distro are you using right now?

![image](https://user-images.githubusercontent.com/68562536/175362673-4ca92567-ef44-4154-8923-ab8b76d319b0.png)
Im using Arch Linux

**Comment by matinlotfali** [comment]
Okay, may I also have the name of the app?
Is that the case with all apps?
-- 

--
*Matin Lotfaliei*
IT Technician & Developer at MistyWest
MSc Student at Department of Computer Science University of Victoria
Pronouns: he, him, his
(604) 785-8161 <+16047858161>  |  Linkedin
<https://www.linkedin.com/in/matinlotfali/>  |  GitHub
<https://github.com/matinlotfali>

**Comment by sheeepdev** [comment]
> Okay, may I also have the name of the app? Is that the case with all apps? --
> […](#)
> -- *Matin Lotfaliei* IT Technician & Developer at MistyWest MSc Student at Department of Computer Science University of Victoria Pronouns: he, him, his (604) 785-8161 <+16047858161> | Linkedin <[linkedin.com/in/matinlotfali](https://www.linkedin.com/in/matinlotfali/)> | GitHub <[@matinlotfali](https://github.com/matinlotfali)>

It is the same for all apps, but the one I have open is firefox

**Comment by matinlotfali** [comment]
It should be fixed now.
