### ISSUE TITLE
Effect's outline conflicts with decoration outline

### ISSUE THREAD

**Issue by demonich** [matinlotfali/KDE-Rounded-Corners#180]
Hello. I think this should be mentioned in the "Tips" section of the README

In KDE Plasma 6, window decoration now has its own outline settings, which should be set to "disabled".
Otherwise strange glitches appear.

if plasma's outline is enabled (double outline?)
![изображение](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/74813436/4edd8a15-ef3a-494b-872d-0b693cc72c1b)
![изображение](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/74813436/c12d1f50-6592-42d5-943a-fc7591ddda36)

if plasma's outline is disabled (correct)
![изображение](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/74813436/b4577a40-c24b-4885-a516-e325b1948acd)

_English is not my native language, sorry._

**Comment by matinlotfali** [comment]
Hi @demonich.

Can you edit the README.md yourself and add the instructions about how to remove the native outline?

Note: the outline has been around since plasma 5.27 (one version before plasma 6)
