### ISSUE TITLE
Build error on Tumbleweed 20240313 after Plasma 6 update

### ISSUE THREAD

**Issue by RedBearAK** [matinlotfali/KDE-Rounded-Corners#182]
@matinlotfali 

The package list for openSUSE was working for Plasma 5 on Tumbleweed, but now that the system has updated to Plasma 6 it doesn't seem to be adequate to resolve build errors. 

```sh
-- Could NOT find KF6ConfigWidgets (missing: KF6ConfigWidgets_DIR)
-- Could NOT find KF6ConfigWidgets: found neither KF6ConfigWidgetsConfig.cmake nor kf6configwidgets-config.cmake 
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find KF6 (missing: ConfigWidgets) (Required is at least version
  "5.78")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF6.cmake:93 (find_package_handle_standard_args)
  CMakeLists.txt:35 (find_package)
```

I tried installing this, it didn't help: 

```sh
kf6-kwindowsystem-devel
```

And I have this installed already, but still get the error: 

```sh
libKF6ConfigWidgets6
```

Right now I don't know what else to look at.

**Comment by aaronkirschen** [comment]
These are what I needed to build on Plasma 6 on Tumbleweed:

```
sudo zypper in cmake gcc-c++ kf6-kconfigwidgets-devel kf6-kcmutils-devel kwin6-devel kf6-kwindowsystem-devel qt6-quick-devel qt6-core-private-devel
```

**Comment by RedBearAK** [comment]
@aaronkirschen 

Thanks, that seems to have resolved everything. 

@matinlotfali 

I was able to get the effect installed and working again with that updated package list from @aaronkirschen. Probably a good idea to update the README with separate package lists for Plasma 5/6, like you did for Fedora. Most Tumbleweed users either already updated to Plasma 6 or will be updated the next time they do a `zypper dup`. 

I do still see the frequent flashing in Wayland for pop-up dialogs in Firefox. Doing a window switch resolves it. Maybe I should file a bug report with KDE for that. But it only happens when this desktop effect is enabled, so there has to be some kind of interaction there.

**Comment by matinlotfali** [comment]
Thanks to @aaronkirschen, the OpenSUSE build dependencies are merged in README.md
