### ISSUE TITLE
effect doesn't work on my 2nd vertical display with tiling

### ISSUE THREAD

**Issue by 4nyNoob** [matinlotfali/KDE-Rounded-Corners#184]
effect doesn't work on my 2nd vertical display with tiling
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/113947854/b923e694-6144-4405-839d-f187f679ed9d)
that might be me not uninstalling the effect correctly (or not rebooting) i did the:
```bash 
sh ../tools/unload.sh
sudo make uninstall 
``` 
thingie and reinstalled the latest release of the plugin via a git clone as the install instructions list it

**i'm currently running:** 
Fedora Linux 39 (KDE Plasma) x86_64
Plasma 5.27.11
6.7.9-200.fc39.x86_64
NVIDIA GeForce RTX 3060 Lite Hash Rate

**Comment by matinlotfali** [comment]
I have made changes to the tiling in #206. Can you check again and tell me if the issue is still present?

**Comment by 4nyNoob** [comment]
> I have made changes to the tiling in #206. Can you check again and tell me if the issue is still present?

it's working flawlessly since 0.6.2 i didn't update to the latest release but it's already good enough for me :) 
thanks for the amazing work
