### ISSUE TITLE
Build instructions for Plasma 6?

### ISSUE THREAD

**Issue by ryu-ketsueki** [matinlotfali/KDE-Rounded-Corners#186]
The readme on Master is still listing the dependencies for Plasma 5. Since this also supports Plasma 6, could there be a specific section for Plasma 6?

**Comment by matinlotfali** [comment]
There are instructions for Plasma6 dependencies for Ubuntu, Fedora, and OpenSUSE.

I assume you are asking for dependencies in another distribution?

**Comment by ryu-ketsueki** [comment]
When I opened this issue, the dependencies for OpenSUSE were still not in master but on a Pull request. I followed that and managed to compile, so this issue can be closed as resolved. Unfortunately, I have another issue, and that is I require an RPM package in order to install this effect, as I cannot install with `sudo make install` due to Micro OS having a read-only root filesystem.

**Comment by matinlotfali** [comment]
I will try to create an RPM using cmake
