### ISSUE TITLE
Autoupdate script runs when DE is not Plasma

### ISSUE THREAD

**Issue by RedBearAK** [matinlotfali/KDE-Rounded-Corners#192]
Should probably do some environment checking in the auto-update startup script. It will run even if the user is not logging into KDE Plasma. I had it pop up some KDialogs after logging into GNOME 46 on the same system, and the same happened the next time I logged into GNOME after logging out (of GNOME).

The install process of course fails if not logged into Plasma, probably for similar reasons that running the Extension Manager Flatpak app in Plasma won't show any GNOME extensions installed. Wrong environment. 

The way that I detect KDE for my own project is by trying to check a couple of environment variables. This is Python: 

```py
    _desktop_env = os.environ.get("XDG_CURRENT_DESKTOP") or os.environ.get("XDG_SESSION_DESKTOP")
```

That first one is usually sufficient on most distros, and I think it shows "KDE" normally, but you might want to do a case-insensitive match in case it's "kde". I have some other fallback checks like looking for the `plasmashell` process or variants of `kwin`, and also remap "Plasma" to be "kde" in case that ever pops up, but I'm pretty sure the current desktop variable usually just says "KDE". 

Another possibly simpler check is just to look for the `KDE_SESSION_VERSION` environment variable. That should always be set if you are actually logged into a Plasma session.

**Comment by matinlotfali** [comment]
@RedBearAK 
Does Pull request #194 probably fix the issue?

**Comment by RedBearAK** [comment]
> @RedBearAK Does Pull request #194 probably fix the issue?

That will quite likely take care of it.

**Comment by RedBearAK** [comment]
@matinlotfali 

Confirming that I don't see the KDialogs popping up when logging into GNOME now. Followed the same install procedure with a new clone and ran the same command to install the auto-update script.
