### ISSUE TITLE
Makes all windows go nearly totally black (no HDR)

### ISSUE THREAD

**Issue by jonwilts** [matinlotfali/KDE-Rounded-Corners#199]
Hi - just installed and tested this out, and it immediately makes all of my windows go nearly totally black - entirely unreadable/unusable.

Moving a window makes it appear normal, and I can see that they do have rounded corners. As soon as I stop moving them - totally black.

Nothing obvious in journalctl.

This is under Plasma 6.0.3. I do not have an HDR capable monitor, so that option is not enabled under Display Settings.

Anything I can do to help debug this?

**Comment by matinlotfali** [comment]
Recently fixed in #193
