### ISSUE TITLE
Ability to switch between whitlist and blacklist

### ISSUE THREAD

**Issue by mufeedali** [matinlotfali/KDE-Rounded-Corners#200]
I want to apply the effect only for some specific applications. Adding every other application to exclusions seems like the only way. Am I missing something? Is this currently posible?

**Comment by mufeedali** [comment]
Oh, may I know why not?

**Comment by matinlotfali** [comment]
Honestly, I thought nobody would ever use it. But if I was wrong, I can add it back.
