### ISSUE TITLE
Disable roudness and outline on tile/maximize does not work

### ISSUE THREAD

**Issue by HanM23** [matinlotfali/KDE-Rounded-Corners#204]
Hello,

First, thank you for this great tool.
I am using Breeze Windows Decorations and Outile Intensity is off. Below are screenshot of what i get with different options :

**Disable Roudness on Tile/Maximize:**
![2024-04-06_14-05](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/38059479/64039d87-611f-4253-b673-1ff6a2514d96)

![2024-04-06_14-45](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/38059479/cbb7e192-6ae8-4025-b682-25baa9ce240e)

**Disable Roudness on Tile/Maximize AND Disable Outile on Tile/Maximize:**
![2024-04-06_14-10](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/38059479/b5d4ce13-6a40-4a14-9665-0d07dbd0fe1e)

![2024-04-06_14-46](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/38059479/7de1cde0-3a1b-417b-87e7-4884c1caeba9)

Whatever i choose to disable Roundness or/and Outile, it's still there, you can see it on both pictures right top corner.
Outline only disappear on Tile/Maximize when i set it to 0 in you application.

Do i do something bad ? I installed it on AUR.
Thank you

**Comment by matinlotfali** [comment]
Sorry, I am a bit confused. So you want round corners when your windows are maximized and unchecking the "Disable Roudness on Tile/Maximize" wouldn't do that?

If that is the case, mine is working fine. So there must be something else causing the issue and I need more information about your setup. 
- Are you using X11 or Wayland? 
- Are you on plasma 5 or 6?
- How many monitors are you using? 
- Is it happening on all monitors?

**Comment by HanM23** [comment]
> Sorry, I am a bit confused. So you want round corners when your windows are maximized and unchecking the "Disable Roudness on Tile/Maximize" wouldn't do that?
> 
> If that is the case, mine is working fine. So there must be something else causing the issue and I need more information about your setup.
> 
>     * Are you using X11 or Wayland?
> 
>     * Are you on plasma 5 or 6?
> 
>     * How many monitors are you using?
> 
>     * Is it happening on all monitors?

Hello,

I do not want round corners when windows are maximized, but currently, that's what i get, hence the screenshots .
Below is a screenshot of the options, so in theory, i should not have rounded corners when i maximize windows.

![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/38059479/3f5224bf-c80b-4751-bf4f-882d0535facd)

My setup : 

Are you using X11 or Wayland?--> X11
Are you on plasma 5 or 6?                  6
How many monitors are you using?--> 1
Is it happening on all monitors? --> N/A

Thank you

**Comment by xiota** [comment]
I checked the AUR package as built by chaotic-aur (0.6.1.r23.gbc4c2e1), and it seems to be working as expected.  I am using X11, Plasma 6.

**Comment by HanM23** [comment]
> I checked the AUR package as built by chaotic-aur (0.6.1.r23.gbc4c2e1), and it seems to be working as expected. I am using X11, Plasma 6.

Hello,

Surprisingly, i do not have any issue anymore, i restored a btrfs snapshot of my system and everything is fine on maximizing windows
