### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by kamikazebob** [matinlotfali/KDE-Rounded-Corners#208]
Unfortunately, getting the below errors when trying to install.... any help much appreciated!

Kubuntu 22.04 Plasma 5

CMake Error at /usr/share/cmake-3.22/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "FindKF5ConfigCore.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "KF5ConfigCore", but CMake did not find one.

  Could not find a package configuration file provided by "KF5ConfigCore"
  (requested version 5.89) with any of the following names:

    KF5ConfigCoreConfig.cmake
    kf5configcore-config.cmake

  Add the installation prefix of "KF5ConfigCore" to CMAKE_PREFIX_PATH or set
  "KF5ConfigCore_DIR" to a directory containing one of the above files.  If
  "KF5ConfigCore" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/KWinEffects/KWinEffectsConfig.cmake:40 (find_dependency)
  CMakeLists.txt:51 (find_package)

**Comment by matinlotfali** [comment]
You need to upgrade to plasma 5.27 using the kubuntu backports ppa:

https://launchpad.net/~kubuntu-ppa/+archive/ubuntu/backports
