### ISSUE TITLE
Feature Request: Draw Outline

### ISSUE THREAD

**Issue by RomanKode** [matinlotfali/KDE-Rounded-Corners#21]
Most of the "Korner" Bug stems from either shadows or Blur, two things I don't fully care for when theming my desktop, so I don't mind limiting blur to just the panel and removing window shadows, the problems is mainly that when you remove the window(decoration) shadow the windows blend in with one another, and basically you do not know when one begins and the other ones ends.

So if the feature to outline the window alongside it's rounded corners it will any and every window a way tot tell them apart and it will give both Qt and GTK apps a level of consistency when rounding their corners.

**Comment by SATYADAHAL** [comment]
This is another feature on my wish list. Hope to see the changes soon.

**Comment by SATYADAHAL** [comment]
Now shape corner doesnot work with no titlebar and frame.
I generally use kde without titlebar and frames but this update doesnot works without 
titlebar and frames. Is there a way around this?

**Comment by matinlotfali** [comment]
@SATYADAHAL 
I was not expecting to see such a need. I reverted the limit back in commit [50d131d](https://github.com/matinlotfali/KDE-Rounded-Corners/commit/50d131de556c55a9ed8332c22c84df7f57cd55a8) to how it used to be.

**Comment by SATYADAHAL** [comment]
**@matinlotfali** 
 Thanks for having this feature back. I love to use KDE without any sort of borders and titlebar.
