### ISSUE TITLE
"Enable animation between active and inactive state" leads to heightened gpu wattage

### ISSUE THREAD

**Issue by tjumar** [matinlotfali/KDE-Rounded-Corners#220]
Hello,
if "Enable animation between active and inactive state" is enabled my rx6700 clocks from 96Mhz memory clock to the next highest state 456Mhz and increases wattage on an idling desktop by ~10-12W.
With the option disabled and desktop idling the memory and gpu clocks return to their deepest state again and normal wattage.

GPU infos can be looked at via a tool like nvtop (newer versions also work for amd and intel).

**Comment by jonwilts** [comment]
Thank you!

For the last few days I've been seeing the CPU usage on my laptop go up significantly - fans constantly running and battery draining super fast. I've been trying to isolate the problem, and tracked it down to KDE-Rounded-Corners. Just saw your post, re-enabled the Effect, but turned off the animation between active/inactive states, and CPU usage is back to normal. 

Old 2015 MacBook Air running KDE with integrated intel GPU so I imagine some of the work was being offloaded to the CPU.

**Comment by matinlotfali** [comment]
@tjumar @jonwilts Can you test #224 and see if it fixes the GPU/CPU issue?

**Comment by tjumar** [comment]
Yes, seems to work fine now with this commit, no change in clocks when enabling the animation option!

**Comment by jonwilts** [comment]
Yes agreed - seems much better. Thank you.
