### ISSUE TITLE
Ability to force outline opacity to 100% regardless of the window opacity

### ISSUE THREAD

**Issue by taj-ny** [matinlotfali/KDE-Rounded-Corners#221]
The outline color is affected by window opacity, resulting in an opaque window's outline being darker than a transparent window's outline. If the window has both opaque and transparent regions, there's a very noticeable difference.

Notice how almost every window in this screenshot has a different outline color.
![outline](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/79316397/87081e13-92ee-4cc6-b6c6-68a1071dfe8d)

EDIT: Perhaps it would be better if the outline opacity depended on the opacity of the window, instead of the opacity of the pixel where the outline is drawn. An option to force 100% opacity would still be nice though.

### Additional information
KDE-Rounded-Corners: v0.6.5
KDE Plasma: v6.0.4

This problem occurs on X11, Wayland and also when the blur effect is disabled.

**Comment by matinlotfali** [comment]
Does #225 do the job?

**Comment by taj-ny** [comment]
Yes.
