### ISSUE TITLE
The effect fails to hide the outline

### ISSUE THREAD

**Issue by Kevadroz** [matinlotfali/KDE-Rounded-Corners#222]
No matter what I do, the disable outline on maximize option doesn't work.

**Comment by matinlotfali** [comment]
can you send me a screenshot and example applications so I can try to reproduce on my end?

**Comment by Kevadroz** [comment]
Actually it doesn't happen always, but when it happens it happens for the rest of the session, even if I manually disable and re-enable the effect

**Comment by matinlotfali** [comment]
Any news?

**Comment by Kevadroz** [comment]
> Any news?

It hasn't happened since then, something must have updated and fixed the issue, I suggest closing the issue, at least for now.
