### ISSUE TITLE
Text blur when i effect is used

### ISSUE THREAD

**Issue by urizennnn** [matinlotfali/KDE-Rounded-Corners#223]
When I enable the shape corners  effect it makes the text of every application installed on the OS to blur, (it takes them from a 1440p resolution to like a 240p )

**Comment by talentlessguy** [comment]
Same happens to LightlyShaders

see https://github.com/a-parhom/LightlyShaders/issues/130

**Comment by matinlotfali** [comment]
It is a duplicate of https://github.com/matinlotfali/KDE-Rounded-Corners/issues/149
