### ISSUE TITLE
doesn't work on Plasma 6.1

### ISSUE THREAD

**Issue by guiodic** [matinlotfali/KDE-Rounded-Corners#231]
I installed kwin 6.0.90.1 and the plugin doesn't show in "Desktop effects", I tried to rebuild it but still doesn't show.

**Comment by TuxTheAstronaut** [comment]
same here ive tried recompiling twice and rebooted and nothing shows up

**Comment by TuxTheAstronaut** [comment]
try recompiling with the newest version i had same issue till i did that and rebooted

**Comment by guiodic** [comment]
I rebuilt from git...

**Comment by FeyrisTan** [comment]
I can confirm rebuilding it works.

**Comment by guiodic** [comment]
Does it work with kwin 6.0.90.1?

**Comment by matinlotfali** [comment]
I would be happy to help but I don't know how to obtain that specific version.
Which distro are you using?

**Comment by guiodic** [comment]
I took kwin 6.0.90.1 (it's the 6.1 beta) from Arch linux kde-unstable repo

**Comment by matinlotfali** [comment]
I successfully installed and activated the effect on Arch Plasma 6.0.90 without any issues.
I guess @guiodic has something else stopping the effect from showing up which is unrelated to the project.

![Arch Linux-2024-05-26-16-00-18](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/7337168/79a3b2c6-54f7-42c1-be2f-8b5df2ff9baf)

**Comment by guiodic** [comment]
I want to apologise because I now realise that the problem does not concern this plugin but another one with the same function. I feel very stupid.

To apologise I will now install this very plugin which does work!

**Comment by matinlotfali** [comment]
No problem at all. I also learned how to get ahead of KDE neon unstable. So it was a win for me.
