### ISSUE TITLE
Keep the origin outline of the program

### ISSUE THREAD

**Issue by songhd** [matinlotfali/KDE-Rounded-Corners#235]
Thanks for this great plugin. 

I'm curious that in some programs like JetBrains IDEs, there is already a light grey outline exists. 

Could we keep this outline to avoid line breaks, both in main window and float window.

![jetbrains-float-window-outline](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/6183393/89f384f4-8fcf-41d4-ae3c-f580cf8fbcc4)
![jetbrains-outline](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/6183393/70cc8c37-01ca-4e12-a0f2-340a3a89f04a)

**Comment by matinlotfali** [comment]
I don't have control over the contents of the window. However, you can use the primary outline in the effect configurations which will render on top of the contents.
