### ISSUE TITLE
OpenSUSE Binary Request

### ISSUE THREAD

**Issue by 8bitZeta** [matinlotfali/KDE-Rounded-Corners#236]
This is more of a request than an issues, but it would be very nice to have an RPM or an OBS repo for the OpenSUSE users.

**Comment by matinlotfali** [comment]
Are you asking for Tumbleweed? or Leap?

**Comment by 8bitZeta** [comment]
Preferably Tumbleweed. If it's possible to support x86, x86-64, and aarch64, that would be fantastic. 

If the latter is too much to ask, I definitely understand.
