### ISSUE TITLE
Broken on KDE 6.1

### ISSUE THREAD

**Issue by GloriousEggroll** [matinlotfali/KDE-Rounded-Corners#243]
looks like its broken again on KDE 6.1, doesn't appear in settings even though installed.

**Comment by ryzendew** [comment]
i can confirm it did break on fedora 41 with plasma 6.1

**Comment by scgm0** [comment]
Everything is fine here for me
![图片](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/52148221/aee78dde-3091-4f2b-892c-9713192b0266)

**Comment by nikoraasu** [comment]
Broken for me also, missing from the "Desktop Effects" setting

**Comment by GloriousEggroll** [comment]
> Everything is fine here for me ![图片](https://private-user-images.githubusercontent.com/52148221/341587008-aee78dde-3091-4f2b-892c-9713192b0266.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MzYxODgsIm5iZiI6MTcxODkzNTg4OCwicGF0aCI6Ii81MjE0ODIyMS8zNDE1ODcwMDgtYWVlNzhkZGUtMzA5MS00ZjJiLTg5MmMtOTcxMzE5MmIwMjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDAyMTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMDYzNzFkNjk2OTg2NmIwNjA4OTE5NTdlZjg0NTM5NmZlYzM3YTdiNWUzOWQ2M2Q2Y2ZhYTg3MzgzYTIxNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.glXWlKwb4Tot7IxhsRWaMbsSJ1uyL0-_hIPHBMzGfT4)

weird that yours works. my guess only guess is maybe you havent rebooted/relogged since the upgrade

**Comment by matinlotfali** [comment]
It is fine on my side too
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/7337168/7ee30861-6971-41f1-ac9f-c0ba89e1d512)

**Comment by matinlotfali** [comment]
@GloriousEggroll @nikoraasu @ryzendew 
May I ask you all to do a clean build with [debug-messages](https://github.com/matinlotfali/KDE-Rounded-Corners?tab=readme-ov-file#add-debug-messages) and send me the logs?

**Comment by 0xarch** [comment]
**Rebuild & install** after upgraded to Plasma 6.1 fixed this problem on my arch-linux

**Comment by matinlotfali** [comment]
@0xarch you need the [auto-install tool](https://github.com/matinlotfali/KDE-Rounded-Corners?tab=readme-ov-file#auto-install-after-kwin-update) for after KWin updates.

**Comment by bitterseeds** [comment]
A recompile worked for me as well on EndeavorOS with KDE 6.1

**Comment by nikoraasu** [comment]
Can confirm, clean building fixed the issue on Arch Linux

**Comment by GloriousEggroll** [comment]
bah i fixed it. somehow kwin -- and only kwin -- was not updated on my system :facepalm: . Updated kwin, rebuilt. working now.
