### ISSUE TITLE
1 pixel transparent border around maximised windows

### ISSUE THREAD

**Issue by noxifoxi** [matinlotfali/KDE-Rounded-Corners#246]
For a few days, when having "Disable Outline on Maximize" set, the outline is not properly removed on maximised windows and a transparent 1 pixel border is revealing whatever is behind (mostly the wallpaper):
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/293639/4ceb032b-636a-4bd1-bf46-9feebc14fe90) 
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/293639/3770d480-b35b-49aa-a441-c1b73de2e39d)

Settings:

![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/293639/f3e25fba-f96c-4980-932b-e101853797b5)

**Comment by OlegAckbar** [comment]
Can confirm this.

**Comment by matinlotfali** [comment]
I have some questions:
- Is it on X11 or Wayland?
- Does it also happen when you disable the animation in the first tab?

**Comment by OlegAckbar** [comment]
@matinlotfali 

- Wayland
- Yes it does
It is also happening for fullscreen apps. Here's an example (I've made and additional black border to make the issue more clearly.
![Снимок экрана_20240630_210604](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/9915567/9237aebd-1d6b-4140-81d3-2408aefe93bb)

**Comment by matinlotfali** [comment]
It should be fixed in #247.
@OlegAckbar can you test it as well?

**Comment by noxifoxi** [comment]
> It should be fixed in #247.

This seems to have fixed the issue after a relog. 👍🏻
