### ISSUE TITLE
Unusual "ًR" character in "ًRound-Corners" group inside options.kcfg

### ISSUE THREAD

**Issue by BBFifield** [matinlotfali/KDE-Rounded-Corners#248]
https://github.com/matinlotfali/KDE-Rounded-Corners/blob/ce087606b74258969ef0465cebe08fa83d724e8d/src/kcm/options.kcfg#L8

Only discovered this because I tried declaring it in my config on NixOS.

Really did feel like something strange was making this specific group not bind, so while it was a relief to finally see what caused this issue, it was also a little embarrassing after realizing the amount of time it took to find :zany_face:.

**Comment by matinlotfali** [comment]
Oh wow! Nice catch!
@BBFifield can you create a pull request?

**Comment by BBFifield** [comment]
> Oh wow! Nice catch! @BBFifield can you create a pull request?

Done! Pull request #249 was created that fixes the typo.
