### ISSUE TITLE
Outlines take padding space inwards & creates visibility issues.

### ISSUE THREAD

**Issue by soymadip** [matinlotfali/KDE-Rounded-Corners#250]
The best way to explain the issue is through example, please focus at padding around the bottom-left `settings` button in below screenshots:

- Script deactivated:-
![for Rounded corners - deactivated](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/84225810/043f6cbd-c566-4602-82e3-351748492e85)

- Script activated:-
![for rounded corners - activated](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/84225810/c19485bd-cdda-4d65-9d71-e4748ed17d0c)

You can see the padding around the settings button is stripped down. 

- This stripping becomes really inconvenient in apps like terminal...

**Comment by matinlotfali** [comment]
Yes, the primary outline goes inward the window. But the secondary outline goes outward the window.

Would making the primary outline fully transparent and only having a secondary outline fixes your issue?

**Comment by soymadip** [comment]
> Yes, the primary outline goes inward the window. But the secondary outline goes outward the window.

Isn't this kinda like bug? I mean who wants to cover their app content?

> 
> Would making the primary outline fully transparent and only having a secondary outline fixes your issue?

Ok I will try it and give you feedback once I go to home...
But I tried to completely disable primary outline and enable secondary outline, it didn't work..

**Comment by matinlotfali** [comment]
> Isn't this kinda like bug? I mean who wants to cover their app content?

Well, there are splash and borderless windows. Because they don't have a shadow, KWin doesn't provide the extra space around the window for me to render on. So they remain without an outline.

So inward outline is currently my only way around that. 

Unless... I find a way to force shadow on shadowless windows.

**Comment by soymadip** [comment]
> Yes, the primary outline goes inward the window. But the secondary outline goes outward the window.
> 
> Would making the primary outline fully transparent and only having a secondary outline fixes your issue?

So i tested this, there are 2 problems:-
- When app is unfocused, there is  a small transparent border, before unfocused border:
![Screenshot_20240708_231535](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/84225810/9e428835-5d1a-4d6f-a090-58e3c55b6be7)

- When the app is in maximized state, the border gets hidden:-
![Screenshot_20240708_233526](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/84225810/c454fdc2-0337-4197-a707-bb24dc689923)
 - And also when windows are tiled (i am using krohnkite.):-
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/84225810/d876d248-8baa-48bb-b4ae-ee14c5a53b26)

**Comment by soymadip** [comment]
> > Isn't this kinda like bug? I mean who wants to cover their app content?
> 
> Well, there are splash and borderless windows. Because they don't have a shadow, KWin doesn't provide the extra space around the window for me to render on. So they remain without an outline.
> 
> So inward outline is currently my only way around that.
> 
> Unless... I find a way to force shadow on shadowless windows.

Oh, i see
