### ISSUE TITLE
Remnant of outline despite it being disabled in the settings

### ISSUE THREAD

**Issue by subhasutra** [matinlotfali/KDE-Rounded-Corners#252]
With KDE Rounded Corners enabled:
![enabled](https://github.com/user-attachments/assets/2a609dbe-174a-4629-9638-231f5b1e1255)
With the effect being disabled:
![disabled](https://github.com/user-attachments/assets/859e225c-540b-461e-838a-4c031c575d47)

In the top left corner, there is a tiny outline which is abruptly cut. In my settings I have both the outlines disabled. Enabling it blends it with the rest of outlines. I'm using Klassy window decorations, but it is there with other decorations too. Is this tiny outline meant to be there always?

**Comment by matinlotfali** [comment]
I confirm that I also see that in Wayland. But not in X11.

**Comment by matinlotfali** [comment]
Actually, it is not the outline, but the shadow.

**Comment by subhasutra** [comment]
Thank you.
