### ISSUE TITLE
Flatpak apps can't be excluded or included reliable

### ISSUE THREAD

**Issue by noxifoxi** [matinlotfali/KDE-Rounded-Corners#255]
Flatpak apps have an empty process name in the `Inclusions & Exclusions` tab. Adding them with this empty name applies this exclusion (or inclusion) to all flatpak apps.

![image](https://github.com/user-attachments/assets/cf18214a-3bbc-4153-9095-5ec6f881eacf)

**Comment by matinlotfali** [comment]
I can't reproduce it on my end. Can you name your distro, plasma version, and display manager?

**Comment by matinlotfali** [comment]
Fixing #239 would probably fix this issue as well.

**Comment by noxifoxi** [comment]
> I can't reproduce it on my end. Can you name your distro, plasma version, and display manager?

- Operating System: Arch Linux (EndeavourOS)
- KDE Plasma Version: 6.1.3
- KDE Frameworks Version: 6.4.0
- Qt Version: 6.7.2
- Kernel Version: 6.9.10-zen1-1-zen (64-bit)
- Graphics Platform: Wayland

**Comment by matinlotfali** [comment]
I installed the exact same items and I still couldn't reproduce the issue.

**Comment by noxifoxi** [comment]
Maybe I'm missing xdg/portal libraries?
I have these installed:
```sh
❯ pacman -Q | grep -i -E "flatpak|xdg|portal"
flatpak 1:1.15.9-1
flatpak-kcm 6.1.3-1
flatpak-xdg-utils 1.0.5-2
libportal 0.7.1-3
libportal-gtk4 0.7.1-3
libportal-qt5 0.7.1-3
libqtxdg 4.0.0-3
python-portalocker 2.10.0-1
python-pyxdg 0.28-3
qtxdg-tools 4.0.0-1
xdg-dbus-proxy 0.1.5-2
xdg-desktop-portal 1.18.4-1
xdg-desktop-portal-gtk 1.15.1-2
xdg-desktop-portal-kde 6.1.3-1
xdg-user-dirs 0.18-2
xdg-utils 1.2.1-1
xdg-utils-cxx 1.0.1-3
```

**Comment by matinlotfali** [comment]
Is this still ongoing?

**Comment by noxifoxi** [comment]
yes, nothing changed.

**Comment by noxifoxi** [comment]
I think it's fixed with the "Class 1, Class 2, Caption" options. But I'm not sure as I reinstalled my OS.
Anyways, I guess it was a me issue. I think it's okay to close this issue.
Thank you for the great work.

**Comment by matinlotfali** [comment]
Thank you for the info. Possibly fixed by #259

**Comment by MiRinChan** [comment]
Have a similar issue here. Version: 0.7.0

![Image](https://github.com/user-attachments/assets/b64d4768-5527-4c97-99e2-3843c1575837)

Operating System: NixOS 25.05
KDE Plasma Version: 6.2.4
KDE Frameworks Version: 6.9.0
Qt Version: 6.8.1
Kernel Version: 6.12.7 (64-bit)
Graphics Platform: Wayland

my system config: https://github.com/MiRinChan/MaybeANixOSConfig

**Comment by matinlotfali** [comment]
@MiRinChan The screenshot of your KDE-Rounded-Corners is not the latest version. The latest version is using a table and not a list for showing windows.

**Comment by MiRinChan** [comment]
> [@MiRinChan](https://github.com/MiRinChan) The screenshot of your KDE-Rounded-Corners is not the latest version. The latest version is using a table and not a list for showing windows.

i see it is my mistake, i see the nixos package site shown it is 0.7.0, but i forget update my system.

let me try it again :/

**Comment by MiRinChan** [comment]
![Image](https://github.com/user-attachments/assets/ae9461c5-eb4b-48f9-acff-c7166453be3f)

it fix thank you!
