### ISSUE TITLE
Add option to disable shadow.

### ISSUE THREAD

**Issue by su226** [matinlotfali/KDE-Rounded-Corners#257]
Please add a option to disable shadow from effect and use shadow from window decoration.

**Comment by matinlotfali** [comment]
Sadly, the window decoration shadow does not cover rounded corners.

Initially, I had to cover those areas myself which did not match the original shadows and people hated it.

So I ended up drawing my shadows myself which allowed me to add animations when the window gets active or inactive.

**Comment by su226** [comment]
> Sadly, the window decoration shadow does not cover rounded corners.

That's not the case for all window decorations. I'm using Klassy, which is fine, I haven't seen issue like #2. (Although you should adjust Klassy's corner radius separately.)

Screenshot using [LightlyShaders](https://github.com/a-parhom/LightlyShaders) since that doesn't override decoration's shadow.

![image](https://github.com/user-attachments/assets/f6aa2742-7e71-49b2-a288-57afa3898ae8)

**Comment by matinlotfali** [comment]
Your examples have a drastic effect on system resources which makes them unusable on low-end devices.
