### ISSUE TITLE
No option to change radius of corner in settings.

### ISSUE THREAD

**Issue by SATYADAHAL** [matinlotfali/KDE-Rounded-Corners#26]
I tried to change the radius of corner by going to Setting -> Desktop Effects -> Shape corners.
But there is no option to change the radius of corner.
Then i tried to search for some configuration file in ~/.config directory . I found a file named  **_shapecornersrc_**
When I looked into file I found this:
> [General]
> Radius=10
> Type=Rounded
> SquareAtScreenEdge=true
> FilterShadow=false
> Whitelist=
> Blacklist=

I changed the radius to 20 but I found no change in the radius of corner. I was wondering if there was some way to change the radius of corner. I am using  kwin 5.24.2

**Comment by matinlotfali** [comment]
I confirm this issue. It is expected to see a settings window. I will check to see why it is not showing up in kwin 5.24

**Comment by SATYADAHAL** [comment]
Just wondering if radius could be changed with some sort of configuration file. The configuration file that I mentioned earlier seems have no change in corner radius . I don't think that configuration file **_~/.config/shapecornersrc_** was related to this project at all. If you could make it work with configuration  file and also from settings it would be great. Hope to see a fix soon.

**Comment by Fxsch** [comment]
You need to create a file called `shapecorners.conf` in `$HOME/.config/`

Inside that file you write:
```
[General]
roundness=20
```
Then you disable and enable shapecorners in the desktop effects.
You can change the 20 to how much rounding you want, 20 is rather high so you'll see wether it works or not.

**Comment by SATYADAHAL** [comment]
It works through the config file. Are there any other options availabe for the config file? Like black listing some apps.

**Comment by SATYADAHAL** [comment]
> You need to create a file called `shapecorners.conf` in `$HOME/.config/`
> ```
> [General]
> roundness=20
> ```

Changing radius with config file works but it also needs to work the settings. And I was wondering if there was more options for 
config file like blacklisting/whitelisting some apps. It would be great to remove rounded corners from apps like Discord.

**Comment by matinlotfali** [comment]
Fixed
