### ISSUE TITLE
No outlines when windows are tiled with Krohnkite

### ISSUE THREAD

**Issue by HonKLam** [matinlotfali/KDE-Rounded-Corners#260]
As far as I know, it looks like the outlines are working when there is one window tiled. However, as soon as there is one more window being tiled through Krohnkite, the outline does the animation to disappear and wont reappear once I focus one of the windows.

It's weird since the animation to fade out the active outline does work when a window is tiled. It just looks like it doesn't know when it's focused when multiple windows are tiled.

Screenshots:

1 Tiled + active window
![image](https://github.com/user-attachments/assets/000520e8-273b-4cf9-a3b6-46d21d289f54)

3 Tiled windows + focused window on the left
![image](https://github.com/user-attachments/assets/8e9d6db6-35bd-4934-ade9-b1bd6ccef390)

3 Tiled windows + focused window on the top right just as the outline starts to fade out although it is focused
![image](https://github.com/user-attachments/assets/e4ef5428-5e38-4127-8484-15c6ef41e41c)

**Comment by matinlotfali** [comment]
Have you configured to disable outlines when tiled?
May I see your configuration window as well?

**Comment by HonKLam** [comment]
> Have you configured to disable outlines when tiled?

Ohhhh that was it. I overlooked that option.. Thank you very much and also great work on the project. I already love it ! <3
