### ISSUE TITLE
CMake error on Kali Linux (Debian Sid)

### ISSUE THREAD

**Issue by ak9473** [matinlotfali/KDE-Rounded-Corners#261]
i am getting error message whenever i try to install on kali linux.

**Comment by matinlotfali** [comment]
I tried Kali Linux and I noticed that ECM has version 6.1 while the KWin is still on 5.27.
This is a condition that I thought would never happen, but I was wrong. 

Choosing the correct KF and QT versions should be decided in another way. I will open a pull request about this.

**Comment by ak9473** [comment]
hey dev i am still getting same error as you mention above. is there any other solution to fix this.

**Comment by matinlotfali** [comment]
Can you send me a copy of the error message?

**Comment by ak9473** [comment]
hi dev i tried in vm now it's working .
Thanks to you now i am going to install kali on my main driver.

**Comment by ak9473** [comment]
again getting same error 

![Screenshot_2024-08-11_06-41-16](https://github.com/user-attachments/assets/126bf812-8737-400a-8a80-16eec3ebfa72)

**Comment by matinlotfali** [comment]
Looks like the build directory is already present.
Can you remove it, build it again, and send me newer logs?

**Comment by ak9473** [comment]
here is the new log .
 i don't know what happened but 4 days before it was working.
![Screenshot_20240812_011457](https://github.com/user-attachments/assets/578628c5-b4fa-4d62-95d6-113c9ba70101)

**Comment by matinlotfali** [comment]
It took me some time to figure out the issue without damaging the installation for other distros.

See #269 

You need to downgrade the `extra-cmake-modules` from the **stable** branch of Debian like this:

```bash
echo "deb http://deb.debian.org/debian stable main" >> /etc/apt/sources.list
apt update 
apt install -t stable extra-cmake-modules 
```

Then, the build should work nicely.
