### ISSUE TITLE
Add whitelist mode

### ISSUE THREAD

**Issue by saihaze** [matinlotfali/KDE-Rounded-Corners#267]
With a proper aurorae decoration theme, only a few apps need kwin-enforced rounded corners. For example, Steam, Tencent QQ, and some Gtk applications. Whitelist mode will allow users to enable the effect only for a few windows and reduce GPU usage.

**Comment by pviscone** [comment]
I was trying to set up this thing. I thought that unchecking "include all normal windows" in the "Inclusions & Exclusions" panel and including just the chosen windows would have worked, but I found a bug.

When you uncheck "include all normal windows", you can't apply the modifications and this will not be saved.
Looking at older issues, there were similar problems [#157].

I think after this fix we will be able to set up a whitelist.

**Comment by matinlotfali** [comment]
@pviscone thanks for pointing it out. I was missing a plural "s" in widget names :see_no_evil:
