### ISSUE TITLE
border is not even

### ISSUE THREAD

**Issue by ColdWater77** [matinlotfali/KDE-Rounded-Corners#277]
![Screenshot_20241002_232844](https://github.com/user-attachments/assets/79bae5ea-e4b4-4a09-83c7-23823a7bd9d1)
look like border is not draw evenly, on the top it draw 2pixel and on the bottom it draw 1pixel

**Comment by matinlotfali** [comment]
May I ask if you are using fractional scaling on your monitor?

**Comment by ColdWater77** [comment]
> May I ask if you are using fractional scaling on your mo
![Screenshot_20241003_143704](https://github.com/user-attachments/assets/384f2473-e4be-4ce9-9679-ea0ab9044b84)
nitor?

yes I'm using 100% scaling, also I also do a bit a research and test and this is probably just KDE thing because it can't even draw its own boarder properly if I enabled "draw border on maximized and tiled windows" it leave 1 pixel gap on the bottom and right side of the screen https://lemmy.ca/pictrs/image/51fde3ca-292a-4d70-b43c-f4f95a6a6639.jpeg

**Comment by ColdWater77** [comment]
Hi, the problem has been fixed on Plasma 6.2
