### ISSUE TITLE
No shapecorner in Settings

### ISSUE THREAD

**Issue by guiodic** [matinlotfali/KDE-Rounded-Corners#28]
Hi, I installed KDE-rounded-corners from AUR but I have'nt shapecorners in KDE Settings. I also tried to restart session but nothig appeared.

**Comment by SATYADAHAL** [comment]
It is duplicate of #26 
You can change radius of roundness by:
https://github.com/matinlotfali/KDE-Rounded-Corners/issues/26#issuecomment-1060751886

**Comment by SATYADAHAL** [comment]
It is a bug. If you want to change the radius of roundness you can have a look at #26

**Comment by matinlotfali** [comment]
I think it is a duplicate of #29
