### ISSUE TITLE
The left and right outlines with be one pixel more than the top and bottom outlines

### ISSUE THREAD

**Issue by scgm0** [matinlotfali/KDE-Rounded-Corners#289]
![图片](https://github.com/user-attachments/assets/71751826-59d4-4f61-bfa9-b09e0fcccc84)
![图片](https://github.com/user-attachments/assets/55241de0-448d-41c7-b3ec-698624470465)
![图片](https://github.com/user-attachments/assets/5676c946-aab1-4250-aade-2c1bd897f071)

#285 caused this issue

**Comment by matinlotfali** [comment]
Reverted. Thanks.
