### ISSUE TITLE
ShapeCorners not showing in settings

### ISSUE THREAD

**Issue by Fire-Ash** [matinlotfali/KDE-Rounded-Corners#29]
I installed this from the AUR, and checked settings for ShapeCorners, but they aren't there.
![image](https://user-images.githubusercontent.com/101067949/167276020-a732a3af-5ffa-44f5-a8fd-c887fdd8d886.png)

**Comment by matinlotfali** [comment]
The AUR is being maintained by @Shaurya-Kalia.

**Comment by Shaurya-Kalia** [comment]
Search for 'corner' after enabling to show unsupported effects from filter list. If its still not visible, could you confirm by removing the aur package and manually compiling

**Comment by Fire-Ash** [comment]
That worked for giving me the option in settings, but when I apply it, it changes nothing.

**Comment by Shaurya-Kalia** [comment]
Your machine does not seem capable to support it. Are you running in VM? Perahaps @matinlotfali can further help with it

**Comment by Fire-Ash** [comment]
I'm not running in a VM. These are my PC's specs if that's helpful in any way.
![image](https://user-images.githubusercontent.com/101067949/167311538-a284e6de-9b87-414f-a586-6d61ea5874b6.png)

**Comment by matinlotfali** [comment]
I don't have arch to try to reproduce the issue. Have you tried to increase the corner radius in settings?

**Comment by Shaurya-Kalia** [comment]
@Fire-Ash Did you reinstall the AUR package or manually install it after kde version update? Reinstalling from AUR solved the issue in a machine of mine.

**Comment by matinlotfali** [comment]
@Fire-Ash Is the issue resolved?

**Comment by Fire-Ash** [comment]
oh i'm sorry. yes it is
