### ISSUE TITLE
Newly opened full-screen windows have rounded corners

### ISSUE THREAD

**Issue by matinlotfali** [matinlotfali/KDE-Rounded-Corners#3]
When you restore and maximize a window, it won't have rounded corners. But when you open a window that is already maximized, it still shows rounded corners.
![Screenshot_20211024_010841](https://user-images.githubusercontent.com/7337168/138585913-24a24812-76e6-4334-95df-9e4808df925a.png)

**Comment by ksinar** [comment]
Any way that we can add an option to enable/disable this if it is merged? I personally prefer to have it stay rounded when maximized.
