### ISSUE TITLE
does not build on latest kde neon

### ISSUE THREAD

**Issue by RedCommand** [matinlotfali/KDE-Rounded-Corners#30]
I'm trying to isntall on kde neon and get and error when running the make command, here is my log :

`[ 15%] Automatic MOC for target kwin4_effect_shapecorners
AutoMoc warning
---------------
"SRC:/shapecorners.cpp"
includes the moc file "shapecorners.moc", but does not contain a Q_OBJECT, Q_GADGET, Q_NAMESPACE, Q_NAMESPACE_EXPORT, K_PLUGIN_FACTORY, K_PLUGIN_CLASS, K_PLUGIN_FACTORY_WITH_JSON or K_PLUGIN_CLASS_WITH_JSON macro.

[ 15%] Built target kwin4_effect_shapecorners_autogen
Consolidate compiler generated dependencies of target kwin4_effect_shapecorners
[ 15%] Building CXX object CMakeFiles/kwin4_effect_shapecorners.dir/shapecorners.cpp.o
/home/maxime/Downloads/KDE-Rounded-Corners/shapecorners.cpp: In member function ‘virtual void ShapeCornersEffect::prePaintWindow(KWin::EffectWindow*, KWin::WindowPrePaintData&, std::chrono::milliseconds)’:
/home/maxime/Downloads/KDE-Rounded-Corners/shapecorners.cpp:213:20: error: ‘class KWin::EffectWindow’ has no member named ‘isPaintingEnabled’
  213 |             || !w->isPaintingEnabled()
      |                    ^~~~~~~~~~~~~~~~~
/home/maxime/Downloads/KDE-Rounded-Corners/shapecorners.cpp:236:14: error: ‘class KWin::WindowPrePaintData’ has no member named ‘clip’
  236 |         data.clip -= rect[i];
      |              ^~~~
/home/maxime/Downloads/KDE-Rounded-Corners/shapecorners.cpp:241:10: error: ‘class KWin::WindowPrePaintData’ has no member named ‘clip’
  241 |     data.clip -=outerRect;
      |          ^~~~
/home/maxime/Downloads/KDE-Rounded-Corners/shapecorners.cpp: In member function ‘virtual void ShapeCornersEffect::paintWindow(KWin::EffectWindow*, int, QRegion, KWin::WindowPaintData&)’:
/home/maxime/Downloads/KDE-Rounded-Corners/shapecorners.cpp:260:20: error: ‘class KWin::EffectWindow’ has no member named ‘isPaintingEnabled’
  260 |             || !w->isPaintingEnabled()
      |                    ^~~~~~~~~~~~~~~~~
/home/maxime/Downloads/KDE-Rounded-Corners/shapecorners.cpp: In static member function ‘static bool ShapeCornersEffect::supported()’:
/home/maxime/Downloads/KDE-Rounded-Corners/shapecorners.cpp:400:58: error: ‘KWin::GLRenderTarget’ has not been declared
  400 |     return KWin::effects->isOpenGLCompositing() && KWin::GLRenderTarget::supported();
      |                                                          ^~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/kwin4_effect_shapecorners.dir/build.make:90: CMakeFiles/kwin4_effect_shapecorners.dir/shapecorners.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:681: CMakeFiles/kwin4_effect_shapecorners.dir/all] Error 2
make: *** [Makefile:166: all] Error 2`

**Comment by RedCommand** [comment]
on latest kde neon unstable get this error :

`make                                                                    16:56:03
[  7%] Automatic MOC for target kwin4_effect_shapecorners
AutoMoc warning
---------------
"SRC:/shapecorners.cpp"
includes the moc file "shapecorners.moc", but does not contain a Q_OBJECT, Q_GADGET, Q_NAMESPACE, Q_NAMESPACE_EXPORT, K_PLUGIN_FACTORY, K_PLUGIN_CLASS, K_PLUGIN_FACTORY_WITH_JSON or K_PLUGIN_CLASS_WITH_JSON macro.

[  7%] Built target kwin4_effect_shapecorners_autogen
[ 15%] Building CXX object CMakeFiles/kwin4_effect_shapecorners.dir/kwin4_effect_shapecorners_autogen/mocs_compilation.cpp.o
[ 23%] Building CXX object CMakeFiles/kwin4_effect_shapecorners.dir/shapecorners.cpp.o
/home/maxime/Downloads/KDE-Rounded-Corners/shapecorners.cpp: In member function ‘virtual void ShapeCornersEffect::prePaintWindow(KWin::EffectWindow*, KWin::WindowPrePaintData&, std::chrono::milliseconds)’:
/home/maxime/Downloads/KDE-Rounded-Corners/shapecorners.cpp:213:20: error: ‘class KWin::EffectWindow’ has no member named ‘isPaintingEnabled’
  213 |             || !w->isPaintingEnabled()
      |                    ^~~~~~~~~~~~~~~~~
/home/maxime/Downloads/KDE-Rounded-Corners/shapecorners.cpp:236:14: error: ‘class KWin::WindowPrePaintData’ has no member named ‘clip’
  236 |         data.clip -= rect[i];
      |              ^~~~
/home/maxime/Downloads/KDE-Rounded-Corners/shapecorners.cpp:241:10: error: ‘class KWin::WindowPrePaintData’ has no member named ‘clip’
  241 |     data.clip -=outerRect;
      |          ^~~~
/home/maxime/Downloads/KDE-Rounded-Corners/shapecorners.cpp: In member function ‘virtual void ShapeCornersEffect::paintWindow(KWin::EffectWindow*, int, QRegion, KWin::WindowPaintData&)’:
/home/maxime/Downloads/KDE-Rounded-Corners/shapecorners.cpp:260:20: error: ‘class KWin::EffectWindow’ has no member named ‘isPaintingEnabled’
  260 |             || !w->isPaintingEnabled()
      |                    ^~~~~~~~~~~~~~~~~
/home/maxime/Downloads/KDE-Rounded-Corners/shapecorners.cpp: In static member function ‘static bool ShapeCornersEffect::supported()’:
/home/maxime/Downloads/KDE-Rounded-Corners/shapecorners.cpp:400:58: error: ‘KWin::GLRenderTarget’ has not been declared
  400 |     return KWin::effects->isOpenGLCompositing() && KWin::GLRenderTarget::supported();
      |                                                          ^~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/kwin4_effect_shapecorners.dir/build.make:90: CMakeFiles/kwin4_effect_shapecorners.dir/shapecorners.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:681: CMakeFiles/kwin4_effect_shapecorners.dir/all] Error 2
make: *** [Makefile:166: all] Error 2`

**Comment by Etaash-mathamsetty** [comment]
also having this issue

**Comment by Etaash-mathamsetty** [comment]
also having this issue

**Comment by matinlotfali** [comment]
Fixed
