### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by ivanthesexy** [matinlotfali/KDE-Rounded-Corners#33]
While building, on step `cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DQT5BUILD=ON` this error shows up:

```
-- Could NOT find KF5Init (missing: KF5Init_DIR)
-- Could NOT find KF5Init: found neither KF5InitConfig.cmake nor kf5init-config.cmake
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find KF5 (missing: Init) (found suitable version "5.94.0",
  minimum required is "5.9.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:93 (find_package_handle_standard_args)
  CMakeLists.txt:33 (find_package)
```

I have no idea how to solve this error, I looked up for "KFS" and "KFSInit" but both showed up results that are unrelated.

Here's the output log file:
[CMakeOutput.log](https://github.com/matinlotfali/KDE-Rounded-Corners/files/8749233/CMakeOutput.log)

**Comment by matinlotfali** [comment]
It is actually KF5 (number five and not the letter S). What is your distro?

**Comment by ivanthesexy** [comment]
> It is actually KF5 (number five and not the letter S). 

Well, that fixed everything. Closing this.

Thanks.
