### ISSUE TITLE
[KWin 5.25] The shadow at the bottom corner behave strangely depending on the movement of the window

### ISSUE THREAD

**Issue by matinlotfali** [matinlotfali/KDE-Rounded-Corners#37]
See the animated screen capture below:

![output](https://user-images.githubusercontent.com/7337168/173905988-f735c1e4-e69d-4bcc-b69f-58947cf1e686.gif)

It gets worse if more windows are on top of each other. I guess it is a repainting issue?

**Comment by matinlotfali** [comment]
This issue is fixed by changing the MASK of paintWindow function

**Comment by matinlotfali** [comment]
Reopening this issue because I am not using MASK in paintWindow anymore and the issue exists

**Comment by zlotny** [comment]
Just to add some testing. I'm experiencing the same behaviour.

Operating System: Arch Linux
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.19.0-zen1-1-zen (64-bit)
Graphics Platform: X11

**Comment by matinlotfali** [comment]
Thanks to @a-parhom, this issue is fixed in #71
