### ISSUE TITLE
Support for GTK windows that don't use native Qt titlebars / borders

### ISSUE THREAD

**Issue by Kaydax** [matinlotfali/KDE-Rounded-Corners#4]
It would be nice to have this since some apps dont have borders enabled by default as it destroys the look of the app. It would be great if there was any way to allow it to support all windows, border or not

**Comment by Kaydax** [comment]
It seems with the latest version, applications like brave no longer have a round border unless it uses system title bars and borders

**Comment by matinlotfali** [comment]
I edited the title to be more specific.

**Comment by matinlotfali** [comment]
The PR #71 should fix this issue
