### ISSUE TITLE
Feature Request: Increase/Decrease the outline thickness.

### ISSUE THREAD

**Issue by SATYADAHAL** [matinlotfali/KDE-Rounded-Corners#46]
Sometimes depending on wallpaper the outline is not properly visible. Can I change it through config file or should i change during build time.

**Comment by matinlotfali** [comment]
We can definitely do that. I need to add it to the configs.

**Comment by matinlotfali** [comment]
@SATYADAHAL can you test #47 (branch [feature/outline-thickness](https://github.com/matinlotfali/KDE-Rounded-Corners/tree/feature/outline-thickness)) and tell me if it is good enough to be merged into master?

**Comment by SATYADAHAL** [comment]
### _**@matinlotfali**_  
**It works perfectly on  Fedora 36 . Loved it. It should be merged into the master.
Now my Fedora looks pretty cool.**

![Screenshot_20220721_194104](https://user-images.githubusercontent.com/51309409/180232024-b016d386-00b9-476a-81cb-45b22f708cf5.png)
