### ISSUE TITLE
The effect is not showing up on Kubuntu 20.04 and Debian 11 anymore

### ISSUE THREAD

**Issue by matinlotfali** [matinlotfali/KDE-Rounded-Corners#51]
The ShapeCorners item is not visible in **Kubuntu 20.04** (KDE Plasma 5.18.8 and KDE Framework 5.68.0) and in **Debian 11** (KDE Plasma 5.20.5 and KDE Framework 5.78.0) anymore.

@alex1701c Could it be related to #41?

**Comment by matinlotfali** [comment]
I tried to revert changes of pull request #41 and it didn't change anything. So it must be something else.

**Comment by alex1701c** [comment]
@matinlotfali Not visible in the sense of it not being showing the the KWin effects KCM?

One idea is to use kdebugsettings, enable debug logs for KCoreAddons, open the KCM using `kcmshell5 kcm_kwin_effects` and check the plugin search paths.

**Comment by matinlotfali** [comment]
> @matinlotfali Not visible in the sense of it not being showing the the KWin effects KCM?

@alex1701c  It does not show up in the Desktop Effects list in the System Settings.

**Comment by alex1701c** [comment]
A very stupid question: Did you search for "ShapeCorners", which is the name specified in the json metadata? I got confused by this at first too.

Checking the plugin search paths and comparing them with the install location might be a good idea. In such old frameworks versions we did not have more detailed log messages when the embedded json metadata could not be loaded.

**Comment by alex1701c** [comment]
>I tried to revert changes of pull request https://github.com/matinlotfali/KDE-Rounded-Corners/pull/41 and it didn't change anything.

Although looking at the source code of this ancient version I find:

```cpp
    const auto pluginEffects = KPluginLoader::findPlugins(
        QStringLiteral("kwin/effects/plugins/"),
        [](const KPluginMetaData &data) {
            return data.serviceTypes().contains(QStringLiteral("KWin/Effect"));
        }
    );
```
Are you sure that reverting https://github.com/matinlotfali/KDE-Rounded-Corners/pull/41/commits/458725ecd8b17e5fa83e1ba539e6698f8cf9c415 does not change anything?

**Comment by matinlotfali** [comment]
Yes, you are right. I put ServiceTypes tag back and it appeared. For its config dialog, I also had to revert the `K_PLUGIN_FACTORY_WITH_JSON`

**Comment by matinlotfali** [comment]
@alex1701c thanks a lot for your hints!

**Comment by alex1701c** [comment]
@matinlotfali NP, please see the comment on the MR though :)
