### ISSUE TITLE
Custom shortcuts not working after installation

### ISSUE THREAD

**Issue by yarinbar** [matinlotfali/KDE-Rounded-Corners#56]
![image](https://user-images.githubusercontent.com/37772157/181428235-034b7f85-913d-41bc-b9a1-4ddf35f645c3.png)

My system:

![image](https://user-images.githubusercontent.com/37772157/181428300-f1705392-75e6-4c63-b0fd-aa2d2ed2984f.png)

**Comment by matinlotfali** [comment]
I can not reproduce it on KDE Neon.
I am also in doubt that it would be related to the project. Can you uninstall the effect and see if the error goes away? If it does, I need to install KDE Fedora to try it out.

**Comment by yarinbar** [comment]
It doesnt go away when i uninstall it, however it did not happen before the installation, so maybe 

`sudo dnf install git cmake gcc-c++ extra-cmake-modules qt5-qttools-devel qt5-qttools-static qt5-qtx11extras-devel kf5-kconfigwidgets-devel kf5-kcrash-devel kf5-kguiaddons-devel kf5-kglobalaccel-devel kf5-kio-devel kf5-ki18n-devel kwin-devel qt5-qtbase-devel libepoxy-devel`

was the problem, however when i removed them it still didnt help. It also affects new users and apparently i cant open dolphin now.

**Comment by matinlotfali** [comment]
I will try it on Fedora and I will get back to you.

**Comment by matinlotfali** [comment]
The custom shortcuts open correctly on my Fedora 36 and the effect turned on. So I guess something else has tampered with your system. I am closing the issue. Feel free to open it again if you find more leads.
