### ISSUE TITLE
corner is not fully transparent

### ISSUE THREAD

**Issue by xAdamQ** [matinlotfali/KDE-Rounded-Corners#59]
I am using Manjaro with x11 there is a slit color change in the corners
![image](https://user-images.githubusercontent.com/29926942/182020601-eb668161-d049-4c57-b4e2-a1ad07e02fcf.png)

it is the same for XWayland, except that the corner effect doesn't even appear on most windows. 

Thanks.

**Comment by matinlotfali** [comment]
@xAdamQ Can you try the branch on pull request #60 and see if the issue is fixed?

**Comment by TobiPeterG** [comment]
> @xAdamQ Can you try the branch on pull request #60 and see if the issue is fixed?

I have the same issue, switched to the pr branch, but the corners are still visible

**Comment by matinlotfali** [comment]
@TobiPeterG from what I see in @xAdamQ 's screenshot, he has disabled the window shadows and corners were not following that setting until pr #60. Is yours the same? May I also see a screenshot and the name of the app?

**Comment by TobiPeterG** [comment]
> @TobiPeterG from what I see in @xAdamQ 's screenshot, he has disabled the window shadows and corners were not following that setting until pr #60. Is yours the same? May I also see a screenshot and the name of the app?

Sorry for the delay, I haven't turned off windows shadows.
I cloned the main repo again and installed it cleanly, still same issue. With small corner radius not really visible, but if set higher, it's really obvious, also in the top: 
![image](https://user-images.githubusercontent.com/19935382/183116599-3841c54d-a045-4f53-876f-993dfc79c9fc.png)

**Comment by matinlotfali** [comment]
Okay @TobiPeterG's issue is different compared to @xAdamQ. To address this, I am guessing that I need to remove all original shadows and draw my own shadows. This probably takes time for me to investigate.

**Comment by TobiPeterG** [comment]
> Okay @TobiPeterG's issue is different compared to @xAdamQ. To address this, I am guessing that I need to remove all original shadows and draw my own shadows. This probably takes time for me to investigate.

Oh okay, thanks for the information! 
Should you need any additional information, feel free to ask. :) 

Should I open a new issue for this or do we keep the discussion here?

**Comment by matinlotfali** [comment]
Let's keep it here.

**Comment by wmyfelix** [comment]
I installed from AUR and there are only corners on the down side of the window. 

X11, Manjaro, window scale 150%

![image](https://user-images.githubusercontent.com/58871134/183462985-8c323c01-bef0-435d-ad0d-ae60c9b4166f.png)

**Comment by matinlotfali** [comment]
@wmyfelix Is it the same when the window scale is %100 ?

**Comment by wmyfelix** [comment]
> @wmyfelix Is it the same when the window scale is %100 ?

Yes. 😿

**Comment by Revincx** [comment]
Hello ! I have the same problem on Plasma 5.26.1, Archlinux, X11 :
![image](https://user-images.githubusercontent.com/25524750/197316544-05152560-1e26-4dd7-8146-4961c923d10c.png)

Is there any new progress ?

**Comment by 13-05** [comment]
same issue, artixlinux with kde; built from source.

![image](https://user-images.githubusercontent.com/64506392/197405194-a41d9bf6-5a42-4917-a4b0-3a9680d35320.png)

**Comment by coffseducation** [comment]
This still affects me.
Kubuntu 20.10
Would Kvantum be in conflict?

**Comment by rew1nter** [comment]
Any updates on this bug?

**Comment by matinlotfali** [comment]
@rew1nter  There has been some progress in the latest release. The corner background issues in @13-05 @Revincx @wmyfelix @TobiPeterG screenshots are fixed. 
They were totally different issues compared to the initial issue that @xAdamQ opened which is about the inconsistency between my corner shadows and native edge shadows.

**Comment by TobiPeterG** [comment]
![image](https://user-images.githubusercontent.com/19935382/215296113-dfc18495-2691-4a3a-9aef-af8dc4e8f670.png)
It got better, but especially the bottom corners are not perfect; on my secondary, scaled display they become almost black

**Comment by matinlotfali** [comment]
Yes, I plan to remove native shadows so I can draw shadows myself so the whole window shadows (edges and corners) would be consistent.

**Comment by rew1nter** [comment]
![image](https://user-images.githubusercontent.com/64508791/219308925-1d444a8b-b7fd-4cb2-94f2-edc254def470.png)
There's this black borderline when no outline is set.

**Comment by matinlotfali** [comment]
@rew1nter nice catch! Can you please submit a new issue for it instead?

**Comment by rew1nter** [comment]
Am I too late to create a new issue? Is there any work going on the bug?

**Comment by newcomb-luke** [comment]
This bug still very much seems to exist even on the new versions. The rest of the window edges are clean but the corners have a bit of a background color and a noticeable black outline.

**Comment by matinlotfali** [comment]
Yes, I am working on it to draw my own shadows instead of the native ones.

**Comment by matinlotfali** [comment]
The fix is implemented and pushed into master.
@xAdamQ @TobiPeterG @Revincx @newcomb-luke 
Thanks for your patience.
