### ISSUE TITLE
Issues building on openSUSE

### ISSUE THREAD

**Issue by linusrg1** [matinlotfali/KDE-Rounded-Corners#63]
I encounter this error when building on openSUSE. I have already installed all the required build packages too.

```
CMake Error at /usr/lib64/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5Network" with
  any of the following names:

    Qt5NetworkConfig.cmake
    qt5network-config.cmake

  Add the installation prefix of "Qt5Network" to CMAKE_PREFIX_PATH or set
  "Qt5Network_DIR" to a directory containing one of the above files.  If
  "Qt5Network" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:17 (find_package)
```
My cmake knowledge is very limited.

**Comment by matinlotfali** [comment]
Maybe @mathiasgredal knows the fix? 
If not, I need to install a fresh OpenSUSE on a virtual machine.

**Comment by bluee111** [comment]
maybe you need to install  libQt5Network-devel , but in Opensuse Leap 15.4 I could not complete success

**Comment by linusrg1** [comment]
@matinlotfali it worked now. So idk what was up before, I am sorry I can't say more than that, because I just don't know what was different this time.

**Comment by matinlotfali** [comment]
No problem. I am glad it is fixed.
