### ISSUE TITLE
Not working in combination with animated background (Shader Wallpaper)

### ISSUE THREAD

**Issue by leonderdunna** [matinlotfali/KDE-Rounded-Corners#67]
![image](https://user-images.githubusercontent.com/79226837/205500264-76f193cd-433c-465e-b0ec-d41d48e32798.png)
kde neon stable 5.26.4 (based on ubuntu 22.04)

**Comment by matinlotfali** [comment]
When I draw corners, I take a picture of the background and place it at the corners. If I take pictures per every frame, it would cost a huge impact on the performance. So I only do that when the window is moving or changing.
That is why animating backgrounds would not work on corners.
One approach to fix this is to make it an option in configs. But I am not sure how many people would want that.
