### ISSUE TITLE
[KWin 5.26.4] Strange header's corners

### ISSUE THREAD

**Issue by SanyaPilot** [matinlotfali/KDE-Rounded-Corners#69]
I have built from latest commit and there's what I'm expecting  

KDE Settings look like this:  
![изображение](https://user-images.githubusercontent.com/29630471/210977693-6e334638-cc7e-4161-a256-fb0544f897b9.png)
And Firefox for example:  
![изображение](https://user-images.githubusercontent.com/29630471/210977859-a435695f-d3ca-4f06-9116-b6032f0c9e85.png)
Although, header's corners doesn't even change. Only bottom ones change  
![изображение](https://user-images.githubusercontent.com/29630471/210978013-6813cde5-1bd7-4170-acca-19dd4bfa29d2.png)

**Comment by matinlotfali** [comment]
PR #71 should fix this issue
