### ISSUE TITLE
Kwin 5.27.0 seems to break this package

### ISSUE THREAD

**Issue by itouchdennis** [matinlotfali/KDE-Rounded-Corners#74]
Hi!

I updated to KDE 5.27.0 with KWIN 5.27.0. 
I recognized, this package is not working anymore.
At first, I guess its caused by the fact, that "kwin" as binary was renamed into kwin_x11 and kwin_wayland - setting symlinks worked, or set up the programm runtime to the exactly needed binary. But then the borders where just for a short time rounded and start beeing buggy.

**Comment by matinlotfali** [comment]
Thanks for letting me know. I will check it out.

**Comment by OrkenWhite** [comment]
Also having issues like this (the terminal emulator is Alacritty):
![Screenshot_20230330_203532](https://user-images.githubusercontent.com/73890378/228920382-958bbc21-55e9-439e-a313-ffc667ddf67b.png)

**Comment by and-win** [comment]
Try Hyprland. It has rounded corners (and other cool features) out of the box.
A week/two of pain to configure and migrate, but it's worth it.
![2023-03-00-05-34](https://user-images.githubusercontent.com/14815839/228965336-a0f00c4f-db38-4b16-a7c6-62fc1644b069.png)

**Comment by OrkenWhite** [comment]
@and-win People using this extension have a reason not to use a proper tiling WM, so we're trying the solve this issue instead of switching to something else...

**Comment by GarlandKey** [comment]
Can confirm. Broken on kwin_x11 & kwin_wayland 5.27.5. Upon applying the desktop effect and refreshing kwin, the rounded corners don't render correctly (see below). When there is a full screen repaint, the effects stop working altogether.

![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/3108516/045136f2-7434-4baf-a496-134ecf5b25eb)

### Specs:
**OS:** Arch Linux x86_64 
**Kernel:** 6.3.2-arch1-1 
**Resolution:** 3840x2160 
**DE:** Plasma 5.27.5 
**WM:** KWin_X11
**WM Theme**: Breeze 
**Theme:** [Plasma], Breeze [GTK3] 
**Icons:** Papirus-Dark [Plasma], Papirus-Dark [GTK2/3] 
**Terminal:** kitty 
**CPU:** AMD Ryzen 7 5700G with Radeon Graphics (16) @ 3.800GHz 
**GPU:** AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
**Memory:** 14271MiB / 23898MiB

**Comment by matinlotfali** [comment]
@itouchdennis @OrkenWhite @GarlandKey 
Fixed. Thanks for reporting the issue.
