### ISSUE TITLE
Window Top Rounded Corners Disappear with Multiple Monitors

### ISSUE THREAD

**Issue by newcomb-luke** [matinlotfali/KDE-Rounded-Corners#76]
KDE Plasma Version: 5.27.4
Arch Linux
X11

I'm not sure how this would occur, but when I plug in my external monitor to my laptop, Firefox refuses to have rounded corners at all, and other applications only have rounded bottom edges, the top is flat. As soon as I unplug my external monitor, the effect resumes working normally.

**Comment by matinlotfali** [comment]
I think I may have fixed this. 
@newcomb-luke Can you update to the latest commit and try again?

**Comment by newcomb-luke** [comment]
I guess you already merged and everything, but yes, it is fixed for me.

**Comment by matinlotfali** [comment]
It is always good to have more eyes checking.
