### ISSUE TITLE
Regarding AUR package

### ISSUE THREAD

**Issue by Shaurya-Kalia** [matinlotfali/KDE-Rounded-Corners#77]
I am currently leaving the maintenance of AUR package to user [xiota](https://aur.archlinux.org/account/xiota) (on AUR). He has created a [new package](https://aur.archlinux.org/packages/kwin-effect-rounded-corners-git) with different name that conforms better to AUR guidelines for package names.
Kindly edit the command to install to `pamac build kwin-effect-rounded-corners-git` in the readme.

**Comment by matinlotfali** [comment]
I also added an arch GitHub workflow to show daily built status.
