### ISSUE TITLE
Rounded rorners and outline after new window is spawned

### ISSUE THREAD

**Issue by kubakakauko** [matinlotfali/KDE-Rounded-Corners#78]
I don't know if it's a feature of a bug however whenever a new window is introduced all windows go back to their default look, rounded corners and outlines are gone.

To bring the rounded corners back I bind a shortcut which runs the `kwin_x11 --replace &` command again however its very inconvenient.

OS: Arch Linux x86_64
Kernel: 6.2.10-arch1-1
 Shell: zsh 5.9
 DE: Plasma 5.27.4
WM: KWin
WM Theme: Bismuth

**Comment by matinlotfali** [comment]
@kubakakauko Fixed. Thanks for reporting the issue.
