### ISSUE TITLE
[Bug] Window outline appears on top of maximised Windows 

### ISSUE THREAD

**Issue by OzzyHelix** [matinlotfali/KDE-Rounded-Corners#79]
I have been facing this issue on my Arch Linux system. Where the outlines of windows under the application I am using would appear on top of the window. The outlines would flicker. 
I fixed this temporary by going  into System Settings > Workspace Behavior > Desktop Effects > ShapeCorners and turning off outline but idk if the problem will reappear.
my hope is reporting it this will might help other users 
![kderoundedcorner-giltch](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/29835364/17d1b356-9cd4-4151-89df-f043563afd14)

**Comment by matinlotfali** [comment]
@OzzyHelix Fixed. Thanks for reporting the issue.
