### ISSUE TITLE
Shadow opacity setting

### ISSUE THREAD

**Issue by Akselmo** [matinlotfali/KDE-Rounded-Corners#84]
Hey, love the effect, but I wish there was a way for setting the shadow opacity.

Thanks :)

**Comment by matinlotfali** [comment]
@Akselmo can you try the branch in #85 and see if adding the alpha channel to the shadow's colour pickers would work for you?

**Comment by Akselmo** [comment]
For some reason the shadow opacity resets after pressing ok in the color picker.

**Comment by Akselmo** [comment]
Probably because of this? https://github.com/matinlotfali/KDE-Rounded-Corners/blob/923f70576dcdc0209f27b33c6bcea34d3325bf9b/shapecorners_config.cpp#LL78C8-L78C8

**Comment by Akselmo** [comment]
Also need to apply the start opacity of the shadow to the shader somehow.

**Comment by matinlotfali** [comment]
You are absolutely correct! My apologies.
I just updated the pull request.
