### ISSUE TITLE
Update to Plasma 5.27.6 uninstalled the ShapeCorners effect

### ISSUE THREAD

**Issue by rafaelhlima** [matinlotfali/KDE-Rounded-Corners#87]
I installed the ShapeCorners 0.4.0 effect from source (following the instructions in the README.md) and all was working very well.

However, yesterday my system updated Plasma to 5.27.6 and the ShapeCorners disappeared from the list of installed effects (via Desktop Effects in the System Settings). As a result, the effect also stopped working.

Is this normal? Do I have to install it again every time Plasma updates? What is the correct course of action now? Is it possible to make the effect persistent across Plasma updates?

I am using Kubuntu 23.04 with backports PPA enabled on Wayland (the problem also happened on my other machine that runs on X11).

**Comment by matinlotfali** [comment]
Sadly, you are right. We need to rebuild and reinstall the effect after each KWin update.
This has been bothering me too.
I wish I knew how to automate this.

**Comment by DostoevskyOnLinux** [comment]
I tried building it from source, but the script isn't showing up in my KWin scripts folder in ~/.local/share/kwin/scripts. This is where two other added KWin scripts live. Am I missing something?

**Comment by matinlotfali** [comment]
@DostoevskyOnLinux On KDE Neon, the plugin installs on:
```
-- Installing: /usr/lib/x86_64-linux-gnu/qt5/plugins/kwin/effects/configs/kwin_shapecorners_config.so
-- Installing: /usr/lib/x86_64-linux-gnu/qt5/plugins/kwin/effects/plugins/libkwin4_effect_shapecorners.so
```
Note that the plugin is not a KWin script, but rather a KWin effect. Therefore, its compiled library files should exactly match the binary of the installed KWin library. This means if the new compilation of the KWin library changes, the effect can not communicate with it anymore and requires a recompilation.

@rafaelhlima I found this pull request on another KWin effect which checks, rebuilds, and reinstalls another effect on every boot: https://github.com/zzag/kwin-effects-yet-another-magic-lamp/pull/60
Maybe we can use adjust it to our effect and use it.

**Comment by rafaelhlima** [comment]
@matinlotfali I do not have any experience with developing Desktop Effects for Plasma, so I don't think I'll be of much help in this matter.

I took a look at the code of other Desktop Effects (f.i. LightlyShaders) and could not figure out "how" and "if" they survive updates. My bet is that they do not survive updates, since a cpp effect would have to be rebuilt against the new libraries at every update.

Maybe you could create a PR to add this effect to KWin directly. This would ensure the effect is built every time and is available for everyone (tbh this effect should be available for everyone to use in the default installation; maybe not enabled by default, but installed by default).

You could also reach out to some experienced Plasma dev to see what they have to say about this.

**Comment by matinlotfali** [comment]
I have been thinking about that too. But it is not a good time. Currently, the Kwin team is working hard to move to Qt 6 and KF6 and I haven't been able to build the effect on their latest branch (i.e. KDE Neon Unstable).

I need to wait until their latest code is stable enough and I can have a clean and usable effect, then I can start the pull request proposal.

Maybe @zzag can also weigh in about this.
