### ISSUE TITLE
The background is dark when the window is transparent and under light theme.

### ISSUE THREAD

**Issue by paletteOvO** [matinlotfali/KDE-Rounded-Corners#90]
With rounded corners:
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/16734391/ba779092-f617-47e1-9ae7-b07805b1917a)

Without rounded corners:
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/16734391/16a46b25-65bc-4ef6-9d48-0deed4fbb2e3)

config:
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/16734391/3db25011-ea1a-4081-a73a-9fef97452eb2)

It looks fine in the dark theme, but it might be because the background is already darkened.

**Comment by matinlotfali** [comment]
Might be related to this line: https://github.com/matinlotfali/KDE-Rounded-Corners/blob/4bf08ddaf047fadde34e285bed51722d9f938290/src/ShapeCornersEffect.cpp#L109C10-L109C24

**Comment by paletteOvO** [comment]
I deleted it and do rebuild/install/restart kwin but nothing is changed.

**Comment by matinlotfali** [comment]
May I know the theme that you are using to replicate it on my end?

**Comment by paletteOvO** [comment]
Every light theme has the same result on my computer, even Breeze.

**Comment by paletteOvO** [comment]
After a few tests, it seems that it is affected by [this line](https://github.com/matinlotfali/KDE-Rounded-Corners/blob/4bf08ddaf047fadde34e285bed51722d9f938290/src/shaders_140/shapecorners.frag#L87), but it would cause another problem if I remove it when there is a shadow:
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/16734391/dffb818a-4a72-484b-90f2-0ae45691533b)

**Comment by paletteOvO** [comment]
After a few random triy I also changed [this line](https://github.com/matinlotfali/KDE-Rounded-Corners/blob/4bf08ddaf047fadde34e285bed51722d9f938290/src/shaders_140/shapecorners.frag#L27) into this:
`return vec4(shadowColor.rgb * percent * (shadowColor.a / 1), shadowColor.a * percent);`
I have totally no idea if there are any side effects, but the result looks fine to me.
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/16734391/c8d98cb1-2731-4b6a-85da-94fc2e98387e)

**Comment by matinlotfali** [comment]
Can you create a pull request so I can check it more?
