### ISSUE TITLE
Error "-- didnt find opengl, not building effects"

### ISSUE THREAD

**Issue by ArchieA** [matinlotfali/KDE-Rounded-Corners#94]
Hi. I'm trying to package for PCLinuxOS and I am following your guide for Fedora. I manage to get most of the BuildRequires: but on cmake .. I get to the point where I get stuck.

I already have our qt5 opengl development package installed and could not determine which others might be needed - freetype, gle or maybe python3-opengl?

I ran Kubuntu on Virtualbox and it built and installed.

Thank you for your attention, and I hope you can assist with this problem.

**Comment by matinlotfali** [comment]
Hi. May I have the output of your `cmake ..`?

**Comment by ArchieA** [comment]
Hi again.

[https://privatebin.net/?2180f6ac84c139a0#ExmQLnPx7F9kQM6jrHn3EnbFxpJyQh1NJNdoYxfTLFGv](url)

...or the last few lines before the error...

> -- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-render.so;/usr/lib64/libxcb-shape.so;/usr/lib64/libxcb-xfixes.so;/usr/lib64/libxcb-shm.so;/usr/lib64/libxcb-util.so;/usr/lib64/libxcb-composite.so;/usr/lib64/libxcb-cursor.so;/usr/lib64/libxcb-damage.so;/usr/lib64/libxcb-dpms.so;/usr/lib64/libxcb-dri2.so;/usr/lib64/libxcb-dri3.so;/usr/lib64/libxcb-ewmh.so;/usr/lib64/libxcb-glx.so;/usr/lib64/libxcb-icccm.so;/usr/lib64/libxcb-image.so;/usr/lib64/libxcb-keysyms.so;/usr/lib64/libxcb-present.so;/usr/lib64/libxcb-randr.so;/usr/lib64/libxcb-record.so;/usr/lib64/libxcb-render-util.so;/usr/lib64/libxcb-res.so;/usr/lib64/libxcb-screensaver.so;/usr/lib64/libxcb-sync.so;/usr/lib64/libxcb-xf86dri.so;/usr/lib64/libxcb-xinerama.so;/usr/lib64/libxcb-xinput.so;/usr/lib64/libxcb-xkb.so;/usr/lib64/libxcb-xtest.so;/usr/lib64/libxcb-xv.so;/usr/lib64/libxcb-xvmc.so (found version "1.14")  
> -- didnt find opengl, not building effects
> CMake Error at CMakeLists.txt:78 (message):
> cant continue
> 
> 
> -- Configuring incomplete, errors occurred!

Also note that I have already installed lib64qt5opengl-devel.

**Comment by matinlotfali** [comment]
I installed PCLinuxOS on a virtual machine, and I found it very frustrating to find packages. 
I wish there was a database of all file contents that one could search for files and it would provide the name of the package that contains it. Other distros have this.
I can't find the `Qt5UiTools.cmake`

**Comment by ArchieA** [comment]
It really takes getting used to. I've been using it for almost 20 years now. I also have Archlinux on bare metal.

Something to help you with your # apt-get install extra-cmake-modules \
gettext \
lib64kf5configwidgets-devel \
lib64kf5globalaccel-devel \
lib64kf5windowsystem-devel \
lib64qt5base5-devel \
lib64qt5designer-devel \
lib64qt5gui-devel \
lib64qt5network-devel \
libr64qt5x11extras-devel \
lib64qt5xml-devel \
lib64xcb-util-cursor-devel

In the meantime, I'm posting on our forum about Qt5UiTools.cmake

Thank you so much for this. It is really appreciated. Hopefully when this is done, a lot of PCLOS KDE users will be able to add a bit more aesthetics to their windows.

**Comment by matinlotfali** [comment]
Fantastic! I successfully built and installed the effect. 

Among the packages related to OpenGL, make sure you have these: `lib64qt5opengl5 lib64qt5opengl-devel`

Here is the list of packages I manually installed (some are probably unneccessary):
https://privatebin.net/?7e84e264a196a542#7w7oBY2VorfLVLxrbWd5n4eCsbvepR2tri8S9Wd89Eve

**Comment by ArchieA** [comment]
I have those two packages already installed. I think I narrowed down the problem...

On my build environment:

[root@localhost SPECS]#  locate Qt5UiToolsConfigVersion.cmake
[root@localhost SPECS]# rpm -qa | grep qt5designer
lib64qt5designer5-5.15.6-1pclos2022
lib64qt5designer-devel-5.15.6-1pclos2022
[root@localhost SPECS]#

But tiles exist in /usr/lib64/cmake/Qt5UiTools/ - Qt5UiToolsConfig.cmake and Qt5UiToolsConfigVersion.cmake

cmake .. just couldn't locate the files.

I think the best route for me is to take a pristine build environment and start all over.

Thank you so much for your help, and I'll consider this issue as solved. I will let you know how it went with PCLinuxOS.

Best regards.
