### ISSUE TITLE
Effect doesn't render correctly if desktop gets focused

### ISSUE THREAD

**Issue by second2050** [matinlotfali/KDE-Rounded-Corners#98]
This effect if switching focus from a window to the desktop seems to not correctly transition the previously active window into the inactive state.

<details><summary>video example</summary>
<p>

https://github.com/matinlotfali/KDE-Rounded-Corners/assets/37344371/b441583d-2a79-4827-8023-21cfc3992631

</p>
</details> 

More info:
Effect Version: 0.4.1.r1.ged77d1e-1

System info:
OS: Arch Linux with ALHP x86-64-v3
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Graphics Platform: X11
GPU: NVIDIA GeForce GTX 1070

**Comment by matinlotfali** [comment]
Sorry but I can't reproduce. 

One possible reason can be the Nvidia driver you are using. My laptop doesn't have an NVidia GPU and my KDE Plasma (not just my effect) have had graphical issues with specific Nvidia drivers before.

Another possible resolution is to add a repaint call when the desktop gets focused. I can try it out in a pull request and ask you to try it. (cause I can't try it on my end to see if it is fixed)

**Comment by second2050** [comment]
I would be happy to test a possible solution!

On another note,
I was able to get a similar thing happen on my laptop, but there it just flickers for a moment and goes away instead of staying. My laptop uses an Optimus setup with kwin rendering on the Intel gpu.

**Comment by matinlotfali** [comment]
Fantastic. Please test #99

**Comment by second2050** [comment]
I just tried your change and it didn't seem to have any effect on my end, it still exhibits the same bug.

I also realized that this bug does *not* happen near blurred regions of the window:
<details><summary>Video Example incl. the bug with the blur effect disabled</summary>
<p>

https://github.com/matinlotfali/KDE-Rounded-Corners/assets/37344371/be18ab7b-a0cb-4848-b286-9d9deb661f00

</p>
</details>

**Comment by matinlotfali** [comment]
That is a nice clue. I updated the https://github.com/matinlotfali/KDE-Rounded-Corners/pull/99. Please pull the changes and rebuild.

**Comment by matinlotfali** [comment]
That is awesome! I just did some optimization. Please test this last one in #99 and if it works fine, I will merge the change.
